// ============================================================
// FØTEX — UGENS TILBUD
// ============================================================
// SÅDAN GØR DU (hver uge):
//   1. Ret `uge:` til det ugenummer appen viser øverst på forsiden
//   2. Slet de gamle varer og skriv ugens tilbud ind — én linje pr. vare:
//        { navn: 'Kyllingebryst 500g', soeg: ['kyllingebryst'], pris: 27 },
//      - soeg: søgeord MED SMÅ BOGSTAVER — samme ord som i basispriser.ts
//      - pris: pakkeprisen i kr fra avisen
//
// REGLER (håndteres automatisk):
//   - Kun tilbud der er BILLIGERE end basisprisen bliver brugt
//   - Varer der ikke bruges i nogen opskrift gør ingen skade
//   - Matcher uge-nr ikke → alle tilbud ignoreres, appen bruger basispriser
// ============================================================

export const FOTEX_TILBUD: {
  butik: string;
  uge: number | number[];
  varer: Array<{ navn: string; soeg: string[]; pris: number }>;
} = {
  butik: 'Føtex',
  uge: 25,

  varer: [
    { navn: 'Buko flødeost 150-200g', soeg: ['flødeost'], pris: 12 },
    { navn: 'Buko flødeost 150-200g føtex plus', soeg: ['flødeost'], pris: 9 },
    { navn: 'Hakket okse-/kylling- eller okse-/grisekød 400g', soeg: ['hakket oksekød', 'hakket kylling'], pris: 39 },
    { navn: 'Hakket okse-/kylling- eller okse-/grisekød 400g føtex plus', soeg: ['hakket oksekød', 'hakket kylling'], pris: 35 },
    { navn: 'Spisemodne avocadoer 3 stk.', soeg: ['avocado'], pris: 22 },
    { navn: 'Spisemodne avocadoer 3 stk. føtex plus', soeg: ['avocado'], pris: 20 },
    { navn: 'Santa Maria Tex Mex 28-371g', soeg: ['tortilla'], pris: 12 },
    { navn: 'Kellogg’s morgenmad, müsli eller granola 205-450g', soeg: ['müsli', 'granola'], pris: 28 },

    { navn: 'To-go marked 27-250g/180-250ml', soeg: [], pris: 6 },
    { navn: 'To-go marked 27-250g/180-250ml føtex plus', soeg: [], pris: 5 },
    { navn: 'Cocktail 25cl', soeg: [], pris: 7 },
    { navn: 'Cocktail 25cl føtex plus', soeg: [], pris: 5 },
    { navn: 'Danske radiser med top', soeg: ['radiser'], pris: 6 },
    { navn: 'Danske radiser med top føtex plus', soeg: ['radiser'], pris: 5 },
    { navn: 'Træk & luk affaldsposer 15-20 stk.', soeg: [], pris: 7 },
    { navn: 'Træk & luk affaldsposer 15-20 stk. føtex plus', soeg: [], pris: 5 },
    { navn: 'Semper smoothie 90g', soeg: [], pris: 7 },
    { navn: 'Semper smoothie 90g føtex plus', soeg: [], pris: 5 },

    { navn: 'Castus frugtstænger eller Grinebidder 50-120g', soeg: [], pris: 12 },
    { navn: 'Castus frugtstænger eller Grinebidder 50-120g føtex plus', soeg: [], pris: 10 },
    { navn: 'Actimel eller Danonino 300-400g', soeg: [], pris: 15 },
    { navn: 'Actimel eller Danonino 300-400g føtex plus', soeg: [], pris: 10 },
    { navn: 'Samyang, Nongshim eller Nissin kopnudler 65-145g', soeg: ['nudler'], pris: 18 },
    { navn: 'Samyang, Nongshim eller Nissin kopnudler 65-145g føtex plus', soeg: ['nudler'], pris: 16 },
    { navn: 'Starbucks kaffekapsler eller Pukka tebreve 10-20 stk.', soeg: [], pris: 32 },
    { navn: 'Starbucks kaffekapsler eller Pukka tebreve 10-20 stk. føtex plus', soeg: [], pris: 27 },

    { navn: 'Bær eller frugt 200-300g', soeg: [], pris: 15 },
    { navn: 'Bær eller frugt 200-300g føtex plus', soeg: [], pris: 12 },
    { navn: 'Calvet Bourgogne eller Moonlight & Roses 75cl', soeg: [], pris: 79 },
    { navn: 'Calvet Bourgogne eller Moonlight & Roses 75cl føtex plus', soeg: [], pris: 69 },
    { navn: 'Fairy opvasketabs 31-56 stk.', soeg: [], pris: 89 },
    { navn: 'Fairy opvasketabs 31-56 stk. føtex plus', soeg: [], pris: 79 },
    { navn: 'Danske hot wings 2,5kg', soeg: ['kylling'], pris: 99 },
    { navn: 'Danske hot wings 2,5kg føtex plus', soeg: ['kylling'], pris: 85 },

    { navn: 'Tights 5-pak', soeg: [], pris: 229 },
    { navn: 'Tights 5-pak føtex plus', soeg: [], pris: 199 },
    { navn: 'Stor bamse', soeg: [], pris: 249 },
    { navn: 'Stor bamse føtex plus', soeg: [], pris: 229 },
    { navn: 'BT-200 Bluetooth højttaler', soeg: [], pris: 119 },
    { navn: 'BT-200 Bluetooth højttaler føtex plus', soeg: [], pris: 99 },
    { navn: 'BT-500B Bluetooth højttaler', soeg: [], pris: 279 },
    { navn: 'BT-500B Bluetooth højttaler føtex plus', soeg: [], pris: 249 },

    { navn: 'Cheasy yoghurt 1 liter', soeg: ['yoghurt naturel'], pris: 12 },
    { navn: 'Premier Is eller Underground iskasse 300-520ml', soeg: ['is'], pris: 27 },
    { navn: 'Gøl megakøbspølser 1,1-1,25kg', soeg: ['pølser'], pris: 75 },
    { navn: 'God Morgen ØKO juice, God Morgen juice eller Valsølille lemonade', soeg: [], pris: 20 },
    { navn: 'Fiskekonserves, pastasauce eller pesto 105-500g', soeg: ['tun', 'makrel', 'pesto'], pris: 12 },
    { navn: 'Coca-Cola sodavand eller Monster Energy 8x50cl/24x25cl', soeg: [], pris: 79 },
    { navn: 'Slikmarked 84-210g', soeg: [], pris: 20 },

    { navn: 'Coca-Cola sodavand 1,25-1,5 liter', soeg: [], pris: 11 },
    { navn: 'Økologiske grøntsager eller pommes frites 300-600g', soeg: ['grøntsagsmix', 'kartofler'], pris: 12 },
    { navn: 'Baron de Ley eller Antonin Rodet 75cl', soeg: [], pris: 50 },
    { navn: 'Mørbrad af dansk gris 1,65-2,2kg', soeg: ['svinekød'], pris: 119 },
    { navn: 'Godt papir 6 rl. toiletpapir eller 3 rl. køkkenrulle', soeg: [], pris: 10 },
    { navn: 'Always eller Tampax 3-6 pakker', soeg: [], pris: 99 },
    { navn: 'Spiritusmarked 70cl', soeg: [], pris: 149 },

    { navn: 'Den fantastiske bus bog', soeg: [], pris: 299.25 },
    { navn: 'Ude for uden bog', soeg: [], pris: 149.25 },
    { navn: 'Styx bog', soeg: [], pris: 149.25 },
    { navn: 'Træningssko', soeg: [], pris: 349 },
    { navn: 'Slippers', soeg: [], pris: 549 },

    { navn: 'Frugtmarked pr. stk.', soeg: [], pris: 2 },
    { navn: 'Familien Jacobsen pålæg 100g', soeg: ['skinke', 'pølser'], pris: 8 },
    { navn: 'Kohberg familie rugbrød eller protein boller 450-750g', soeg: ['rugbrød'], pris: 12 },
    { navn: 'Økologiske hakkede eller flåede tomater 400g', soeg: ['hakkede tomater', 'flåede tomater'], pris: 6 },
    { navn: 'Økologisk fuldkornspasta 500g', soeg: ['fuldkornspasta'], pris: 8 },
    { navn: 'Tortilla wraps fuldkorn 370g', soeg: ['tortilla'], pris: 8 },

    { navn: 'Samlealbum', soeg: [], pris: 40 },
    { navn: 'Kokosmælk 400ml', soeg: ['kokosmælk'], pris: 8 },
    { navn: 'Tortilla wraps 370g', soeg: ['tortilla'], pris: 10 },

    { navn: 'Hapsermenu pr. kuvert', soeg: [], pris: 95 },
    { navn: 'Sliders pr. stk.', soeg: [], pris: 18 },
    { navn: 'Klassisk brunch pr. kuvert', soeg: [], pris: 125 },
    { navn: 'Festbuffet pr. kuvert', soeg: [], pris: 125 },

    { navn: 'Pedersens udvalgte økologiske danske August tomater 250g', soeg: ['tomat'], pris: 24 },
    { navn: 'Pedersens udvalgte danske pink eller marmande tomater 400g', soeg: ['tomat'], pris: 24 },
    { navn: 'Pedersens udvalgte økologiske danske runde tomater 400g', soeg: ['tomat'], pris: 18 },
    { navn: 'Kirsebær pr. 100g', soeg: [], pris: 7.95 },
    { navn: 'Pedersens udvalgte danske økologiske cherrytomater 200g', soeg: ['tomat'], pris: 15 },

    { navn: 'Tjele Gods økologisk smør 200g', soeg: ['smør'], pris: 34.95 },
    { navn: 'Tjele Gods økologisk skummetmælk 1 liter', soeg: ['mælk'], pris: 13.95 },
    { navn: 'Tjele Gods økologisk kærnemælk 1 liter', soeg: ['mælk'], pris: 14.95 },
    { navn: 'Tjele Gods økologisk minimælk 1 liter', soeg: ['mælk'], pris: 15.35 },
    { navn: 'Tjele Gods økologisk letmælk 1 liter', soeg: ['mælk'], pris: 16.44 },
    { navn: 'Tjele Gods økologisk sødmælk 1 liter', soeg: ['mælk'], pris: 16.95 },

    { navn: 'Grillmarked 7 stk.', soeg: [], pris: 100 },
    { navn: 'Frisklavet luksus smørrebrød', soeg: [], pris: 35 },

    { navn: 'Madbrød', soeg: ['brød'], pris: 20 },
    { navn: 'Surdejsbaguette', soeg: ['brød'], pris: 18 },
    { navn: 'Hvidløgsbrød 350g', soeg: [], pris: 16 },
    { navn: 'Økologiske danske portobellosvampe 250g', soeg: ['champignon'], pris: 20 },
    { navn: 'Grafitti aubergine', soeg: ['aubergine'], pris: 10 },
    { navn: 'Økologisk dansk spidskål', soeg: ['spidskål'], pris: 12 },
    { navn: 'Pedersens udvalgte danske peberfrugter 2 stk.', soeg: ['peberfrugt'], pris: 24 },

    { navn: 'Pitabrød 420g', soeg: ['pitabrød'], pris: 20 },
    { navn: 'Zelected survarer 190-580g', soeg: [], pris: 22 },
    { navn: 'Taverna salatost 400g', soeg: ['salatost'], pris: 25 },
    { navn: 'Pommes gigant steak fries 700g', soeg: ['kartofler'], pris: 25 },
    { navn: 'Udbenede kyllingeoverlår 800g', soeg: ['kylling'], pris: 59 },
    { navn: 'Rose hel kylling eller kyllingebrystfilet 800-1600g', soeg: ['kyllingebryst'], pris: 59 },
    { navn: 'Flæsk i skiver, spareribs eller grillmedister 700-800g', soeg: ['svinekød', 'pølser'], pris: 49 },
    { navn: 'Skagenfood fersk jomfruhummer eller tunsteak 200-350g', soeg: ['tun'], pris: 49.95 },

    { navn: 'Hakket okse- eller grise-/kalvekød 700-1000g', soeg: ['hakket oksekød', 'hakket grisekød'], pris: 79 },
    { navn: 'Nakkefilet eller ribbensteg af dansk gris 1,9-3kg', soeg: ['svinekød'], pris: 129 },
    { navn: 'Tykstegsmedaljoner eller -bøffer 600-650g', soeg: ['oksekød'], pris: 129 },
    { navn: 'Okseculotte pr. 1/2 kg', soeg: ['oksekød'], pris: 89.95 },
    { navn: 'Marineret lammekølle 1,4-1,6kg', soeg: ['lammekød'], pris: 239 },
    { navn: 'Burger BOOST af dansk kød 300-350g', soeg: ['bøffer'], pris: 44 },
    { navn: 'Burger BOOST af dansk kød 300-350g føtex plus', soeg: ['bøffer'], pris: 39 },

    { navn: 'Softkernerugbrød', soeg: ['rugbrød'], pris: 25 },
    { navn: 'Trøffelkugle', soeg: [], pris: 9 },
    { navn: 'Onsdagssnegl', soeg: [], pris: 10 },
    { navn: 'Kanelstang', soeg: [], pris: 30 },
    { navn: 'Surdejsbrød', soeg: ['brød'], pris: 25 },
    { navn: '10 friskbagte rundstykker', soeg: [], pris: 40 },
    { navn: 'Softkernerugbrød tilkøb', soeg: ['rugbrød'], pris: 20 },
    { navn: 'Små morgenkager tilkøb', soeg: [], pris: 7 },
    { navn: 'Morgenkage tilkøb', soeg: [], pris: 25 },

    { navn: 'Mammen skæreost 1,08-1,32kg', soeg: ['ost'], pris: 99 },
    { navn: 'Lurpak smør eller smørbar 200g', soeg: ['smør', 'smørbar'], pris: 22 },
    { navn: 'Riberhus eller Cheasy skiveost 180-240g', soeg: ['ost'], pris: 22 },
    { navn: 'Børnesnacks eller Puck ost 120-500g', soeg: ['ost'], pris: 30 },
    { navn: 'Naturli’ plantedrik, smørbar eller blok 200g/330-1000ml', soeg: ['smørbar'], pris: 15 },
    { navn: 'Arla koldskål eller Arla Cultura Kefir, koldskål eller A38 1 liter', soeg: [], pris: 16 },
    { navn: 'Økologiske danske æg 10 stk.', soeg: ['æg'], pris: 30 },

    { navn: 'Moussekage', soeg: [], pris: 109 },
    { navn: 'Boller 8 stk.', soeg: ['boller'], pris: 35 },
    { navn: 'Kiks- eller kagemarked 80-260g', soeg: [], pris: 15 },
    { navn: 'Pågen brød 360-800g', soeg: [], pris: 15 },
    { navn: 'Leibniz zoo, Toffypops, Salling kanel biscuits eller crispy munchies 100-250g', soeg: [], pris: 11 },
    { navn: 'Wasa knækbrød 110-285g', soeg: ['knækbrød'], pris: 16 },

    { navn: 'Tapas 3 stk.', soeg: ['skinke', 'ost'], pris: 69 },
    { navn: 'Paté 250g', soeg: ['leverpostej'], pris: 12 },
    { navn: 'Sønderjyske Fristelser pålægssalat 140g', soeg: [], pris: 15 },
    { navn: 'Spareribs 500g', soeg: ['svinekød'], pris: 39 },
    { navn: 'Økologisk tørsaltet bacon 100g', soeg: ['bacon'], pris: 22 },
    { navn: '3-Stjernet pålæg 40-125g', soeg: ['skinke', 'pølser'], pris: 12 },

    { navn: 'Mini forårsruller med rejefyld 200g', soeg: [], pris: 20 },
    { navn: 'Champion nuggets 600g', soeg: [], pris: 20 },
    { navn: 'Grønlandske rejer, kold- eller varmrøget laks 175-280g', soeg: ['laks', 'rejer'], pris: 65 },
    { navn: 'Ferske rejer 170-225g', soeg: ['rejer'], pris: 39 },
    { navn: 'Mowi sushi 12 stk.', soeg: [], pris: 45 },
    { navn: 'Mowi sushi 16 stk.', soeg: [], pris: 55 },
    { navn: 'Laksefilet 225g', soeg: ['laks'], pris: 49 },
    { navn: 'Dansk kyllingelår, -inderfilet eller hakket kyllingekød 330-700g', soeg: ['hakket kylling'], pris: 30 },
    { navn: 'Dansk kyllingelår, -inderfilet eller hakket kyllingekød 330-700g føtex plus', soeg: ['hakket kylling'], pris: 89 },
    { navn: 'De Danske Familiegårde kyllingebrystfilet eller -inderfilet 800g', soeg: ['kyllingebryst'], pris: 99 },

    { navn: 'Tortilla wraps fuldkorn 370g', soeg: ['tortilla'], pris: 10 },
    { navn: 'Økologisk dansk spidskål', soeg: ['spidskål'], pris: 12 },
    { navn: 'Frisk rød chili 70g', soeg: ['chili'], pris: 14 },
    { navn: 'Pedersens udvalgte danske økologiske cherrytomater 200g', soeg: ['tomat'], pris: 15 },
    { navn: 'Fraiche 9% 500g', soeg: ['creme fraiche'], pris: 15 },
    { navn: 'Rose hakket dansk kyllingekød 450g', soeg: ['hakket kylling'], pris: 30 },

    { navn: 'Kyllingespyd med kartofler, mexicansk risret eller laks med grønt 1 stk.', soeg: ['kartofler', 'laks'], pris: 49 },
    { navn: 'Kyllingespyd med kartofler, mexicansk risret eller laks med grønt 2 stk.', soeg: ['kartofler', 'laks'], pris: 75 },
    { navn: 'Lørdagskylling 1,15-1,3kg', soeg: ['kylling'], pris: 54.95 },
    { navn: 'Godt Begyndt kyllingespyd med flødekartofler 800-950g', soeg: ['kartofler'], pris: 54.95 },
    { navn: 'Godt Begyndt mørbrad med kartofler 950-1150g', soeg: ['svinekød', 'kartofler'], pris: 79.95 },
    { navn: 'Godt Begyndt krydret mørbrad med flødekartofler 900-1150g', soeg: ['svinekød', 'kartofler'], pris: 79.95 },

    { navn: 'Tortillas med oksekød, schnitzel eller karbonader med tilbehør', soeg: ['oksekød'], pris: 49 },
    { navn: 'Tortillas med oksekød, schnitzel eller karbonader med tilbehør 2 stk.', soeg: ['oksekød'], pris: 75 },
    { navn: 'Delikatessens grillkylling', soeg: ['kylling'], pris: 55 },
    { navn: 'Frisklavet luksus smørrebrød', soeg: [], pris: 35 },
    { navn: 'Delikatessens stjerneskud', soeg: [], pris: 35 },
    { navn: 'Håndskåret entrecoté eller rib-eye 250-275g', soeg: ['oksekød'], pris: 79 },

    { navn: 'Robert Charton Bordeaux eller Charles Aine & Fils Rhone 75cl', soeg: [], pris: 35 },
    { navn: 'Barefoot, My Way eller The Wild Life 75cl', soeg: [], pris: 55 },
    { navn: 'Uno Grande, Star eller Ernst Ludwig Riesling Bag-in-Box 3 liter', soeg: [], pris: 109 },
    { navn: 'San Felice Il Grigio Chianti Classico 75cl', soeg: [], pris: 99 },
    { navn: 'Små vinflasker eller 1,5 liters Bag-in-Box eksempel 69,-', soeg: [], pris: 55.2 },
    { navn: 'Små vinflasker eller 1,5 liters Bag-in-Box eksempel 99,-', soeg: [], pris: 79.2 },

    { navn: 'Spiritusmarked 70-100cl', soeg: [], pris: 129 },
    { navn: 'Powerrade 50cl', soeg: [], pris: 10 },
    { navn: 'Faxe Kondi 75cl', soeg: [], pris: 30 },
    { navn: 'Små shots 70cl', soeg: [], pris: 65 },
    { navn: 'Spiritusmarked 50-70cl', soeg: [], pris: 99 },

    { navn: 'Cocio 25cl', soeg: [], pris: 7 },
    { navn: 'Drikkevaremarked 33cl', soeg: [], pris: 10 },
    { navn: 'Monster Energy 50cl', soeg: [], pris: 14 },
    { navn: 'Drikkevaremarked 50cl', soeg: [], pris: 24 },
    { navn: 'Rynkeby 16 serien eller Rynkeby frisk juice 1 liter', soeg: [], pris: 20 },
    { navn: 'Ribena 85cl', soeg: [], pris: 25 },
    { navn: 'Capri-Sun 10x20cl', soeg: [], pris: 28 },
    { navn: 'Æblemost 3 liter', soeg: [], pris: 40 },

    { navn: 'Steff Houlberg pølser eller Tulip baconsteaks 200-450g', soeg: ['pølser', 'bacon'], pris: 25 },
    { navn: 'KiMs chips 80-170g', soeg: [], pris: 15 },
    { navn: 'Sunshine Delights tørret frugt 100g', soeg: [], pris: 20 },
    { navn: 'Stenovnsbagt pizza 330-395g', soeg: [], pris: 18 },
    { navn: 'Monster Energy 4x50cl', soeg: [], pris: 40 },
    { navn: 'Drikkevaremarked Somersby, Breezer eller Smirnoff Ice', soeg: [], pris: 13 },
    { navn: 'Coca-Cola sodavand 24x33cl', soeg: [], pris: 75 },

    { navn: 'Pasta 500g', soeg: ['pasta'], pris: 12 },
    { navn: 'Sæby makrel eller Salling tun 125-140g', soeg: ['makrel', 'tun'], pris: 13 },
    { navn: 'Graasten marked 375-425g', soeg: [], pris: 19 },
    { navn: 'Zelected eller Foodmood oliven 90-300g', soeg: ['oliven'], pris: 39 },
    { navn: 'Hansens flødeis marked 240-725ml', soeg: ['is'], pris: 49 },
    { navn: 'BKI formalet kaffe 300-400g', soeg: [], pris: 45 },
    { navn: 'Spangsberg, Naturli’ eller Underground is 360-750ml', soeg: ['is'], pris: 32 },
    { navn: 'Helbønnemarked 900-1000g', soeg: [], pris: 159 },

    { navn: 'Toms, Carletti eller Evers marked 60-80g', soeg: [], pris: 10 },
    { navn: 'Taffel 125-175g', soeg: [], pris: 13 },
    { navn: 'Bagemarked 9-2000g', soeg: ['hvedemel'], pris: 20 },
    { navn: 'KiMs nødder 80-235g', soeg: ['nødder'], pris: 16 },
    { navn: 'Green Dates 110-120g', soeg: [], pris: 20 },
    { navn: 'Marabou plade, bites, smil eller Twist 130-180g', soeg: [], pris: 30 },
    { navn: 'Riesen eller Werthers Original 125-135g', soeg: [], pris: 25 },
    { navn: 'Riesen eller Werthers Original 125-135g føtex plus', soeg: [], pris: 22 },
    { navn: 'Myslibar 6-pak 138-150g', soeg: [], pris: 12 },

    { navn: 'Chokoladekage med Sarah Bernhardt', soeg: [], pris: 250 },
    { navn: 'Luksus Othellolagkage', soeg: [], pris: 400 },
    { navn: 'Studenterhue i kransekage med macarons og kransekagekonfekt', soeg: [], pris: 250 },
    { navn: 'Studenterhuelagkage', soeg: [], pris: 799 },

    { navn: 'Bordflag med figur', soeg: [], pris: 30 },
    { navn: 'Fingerprint plakat A4', soeg: [], pris: 30 },
    { navn: 'Studenterkort', soeg: [], pris: 26.95 },
    { navn: 'Konfettirør 30cm', soeg: [], pris: 19 },
    { navn: 'Konfettirør 78cm', soeg: [], pris: 40 },
    { navn: 'Windsor mønstrede servietter 20 stk.', soeg: [], pris: 12 },
    { navn: 'Studenterpynt', soeg: [], pris: 10 },
    { navn: 'Megafon', soeg: [], pris: 79 },
    { navn: 'Vindmølle', soeg: [], pris: 40 },
    { navn: 'Beerpong', soeg: [], pris: 50 },
    { navn: 'Papkrus 40 stk.', soeg: [], pris: 60 },
    { navn: 'Træbestik 20 stk.', soeg: [], pris: 15 },
    { navn: 'Paptallerkner 40 stk.', soeg: [], pris: 75 },
    { navn: 'Smartbox Middag for 2 gavekort', soeg: [], pris: 399.2 },
    { navn: 'Smartbox Tillykke gavekort', soeg: [], pris: 319.2 },
    { navn: 'Rammer', soeg: [], pris: 75 },
    { navn: 'Sort ramme med glas 21x29,7cm', soeg: [], pris: 199 },

    { navn: 'Harpic eller The Pink Stuff', soeg: [], pris: 15 },
    { navn: 'Biotex eller Dunlet vaskemiddel eller skyllemiddel', soeg: [], pris: 25 },
    { navn: 'Vaskemiddel 750ml', soeg: [], pris: 19 },
    { navn: 'Lotus papir', soeg: [], pris: 25 },
    { navn: 'Livol vitaminer/mineraler 150-385 stk.', soeg: [], pris: 79 },
    { navn: 'Libero Comfort eller Up&Go bleer 20-43 stk.', soeg: [], pris: 69 },
    { navn: 'Fitness Pharma Økonomi 60-360 stk.', soeg: [], pris: 115 },
    { navn: 'Nicorette tyggegummi 210 stk.', soeg: [], pris: 249 },
    { navn: 'Nicorette Quickmist duo pak', soeg: [], pris: 379 },

    { navn: '2000 Calorie 2in1 Primer daily UV serum 30ml', soeg: [], pris: 99 },
    { navn: 'Long Lash Era mascara 7,8ml', soeg: [], pris: 115 },
    { navn: 'Kids solcreme SPF50 150ml', soeg: [], pris: 89 },
    { navn: 'Gosh Eyedeal lashes mascara 8ml', soeg: [], pris: 150 },
    { navn: 'Gosh forever mineral eye shadow 1,4g', soeg: [], pris: 130 },
    { navn: 'Medicube collagen night wrapping mask 75ml', soeg: [], pris: 185 },
    { navn: 'Taft Aloe Boost hårspray eller texturizing spray 150-250ml', soeg: [], pris: 20 },
    { navn: 'Stuhr Repair shampoo eller balsam 250-350ml', soeg: [], pris: 59 },
    { navn: 'Cellular Epigenetics serum 30ml', soeg: [], pris: 199 },

    { navn: 'L’Oréal Paris Hyaluron lip stain serum 5ml', soeg: [], pris: 89.25 },
    { navn: 'Head&Shoulders shampoo eller balsam 220-250ml', soeg: [], pris: 22 },
    { navn: 'MONDAY shampoo, balsam eller hårmaske 250-350ml', soeg: [], pris: 49 },
    { navn: 'Solpleje 50-500ml', soeg: [], pris: 89 },
    { navn: 'Aftersun sorbet 200ml', soeg: [], pris: 79 },
    { navn: 'Palmolive shower 500-650ml', soeg: [], pris: 14 },
    { navn: 'Palmolive håndsæbe 300ml', soeg: [], pris: 25 },
    { navn: 'Elizabeth Arden Green Tea kropspleje 500ml', soeg: [], pris: 89 },
    { navn: 'Tigi Bed Head resurrection eller recovery hårpleje 2x750ml', soeg: [], pris: 119 },

    { navn: 'Stuhr Grow my hair shampoo eller balsam 125-150ml', soeg: [], pris: 59 },
    { navn: 'Stuhr Grow my hair serum 5x7ml', soeg: [], pris: 139 },
    { navn: 'Maui eller Ogx hårpleje 118-400ml', soeg: [], pris: 74 },
    { navn: 'Björn Axén hårpleje 150-250ml', soeg: [], pris: 99 },
    { navn: 'Olaplex hårpleje 100-250ml', soeg: [], pris: 189 },

    { navn: 'Elizabeth Arden Eight Hour lip protection stick', soeg: [], pris: 95 },
    { navn: 'Meraki håndlotion, håndsæbe, bodywash eller duftpinde 120-490ml', soeg: [], pris: 99 },
    { navn: 'Biotherm deodorant 75-150ml', soeg: [], pris: 125 },
    { navn: 'Sanzi beauty øjenvippe- eller øjenbrynserum 5ml', soeg: [], pris: 299 },
    { navn: 'Elizabeth Arden hudpleje', soeg: [], pris: 135 },
    { navn: 'M2 beauté øjenvippe- eller brynserum 4ml', soeg: [], pris: 499 },

    { navn: 'Dufte til hende 100ml', soeg: [], pris: 55 },
    { navn: 'Clean edp 30ml', soeg: [], pris: 249 },
    { navn: 'Adidas Vibes edt 50ml', soeg: [], pris: 149 },
    { navn: 'Woman by Gosh deodorant 75-150ml', soeg: [], pris: 35 },
    { navn: 'Adidas Vibes bodymist 150ml', soeg: [], pris: 69 },
    { navn: 'Paco Rabanne deodorant 75-150ml', soeg: [], pris: 169 },
    { navn: 'Dufte til ham 100ml', soeg: [], pris: 55 },
    { navn: 'Calvin Klein eller Davidoff deodorant 75-150ml', soeg: [], pris: 89 },
    { navn: 'Dufte til ham 35-100ml', soeg: [], pris: 299 },
    { navn: 'Cristiano Ronaldo CR7 deodorant 150ml', soeg: [], pris: 39 },

    { navn: 'Corny crunch protein bar, High5 energy bar, Nocco RTD, Crisp proteinbar, Nutramino energi shots eller energi bar', soeg: [], pris: 10 },
    { navn: 'Basic gummies 60 stk.', soeg: [], pris: 35 },
    { navn: 'Magnesium citrat eller multivitamin 50+ 120-150 stk.', soeg: [], pris: 68 },
    { navn: 'Multi-tabs kids vitaminer 60-190 stk.', soeg: [], pris: 99 },
    { navn: 'Kids Zoo vitaminer 60 stk.', soeg: [], pris: 159 },
    { navn: 'Natur Drogeriet B9 folsyre 180 stk.', soeg: [], pris: 47 },
    { navn: 'Dragon super matcha powder 100g', soeg: [], pris: 89 },
    { navn: 'Nordbo Female support menopause 90 stk.', soeg: [], pris: 269 },
    { navn: 'Superfruit bee pollen 200g', soeg: [], pris: 179 },
    { navn: 'Organic kombucha 400ml', soeg: [], pris: 23 },
    { navn: 'Mezina cynaflora eller man power 90 stk.', soeg: [], pris: 169 },
    { navn: 'Nordbo instant magnesium 150g', soeg: [], pris: 135 },
    { navn: 'Aliga Aqutive chlorella/spirulina 200g', soeg: [], pris: 75 },
    { navn: 'Whey med kreatin 400g', soeg: [], pris: 99 },
    { navn: 'Kreatinpulver 300g', soeg: [], pris: 59 },
    { navn: 'Kreatin gummies 60 stk.', soeg: [], pris: 65 },
    { navn: 'Proteinbar med kreatin 55g', soeg: [], pris: 16 },

    { navn: 'Skovlyst øl 50cl', soeg: [], pris: 10 },
    { navn: 'Ølmarked 50cl', soeg: [], pris: 12 },
    { navn: 'Specialøl alkoholfri 75cl', soeg: [], pris: 20 },
    { navn: 'Ølmarked 33-50cl', soeg: [], pris: 10 },
    { navn: 'St. Feuillien Grand Cru 75cl', soeg: [], pris: 60 },
    { navn: 'Willemoes eller Ugly Duck øl 3 stk.', soeg: [], pris: 45 },
    { navn: 'Delirium Tremens 75cl', soeg: [], pris: 69 },
    { navn: 'Grimbergen Quadrupel 75cl', soeg: [], pris: 35 },
    { navn: 'Skovlyst Vintage Selection 75cl', soeg: [], pris: 50 },
    { navn: 'Anarkist øl 5 stk.', soeg: [], pris: 100 },
    { navn: 'Specialøl 5 stk.', soeg: [], pris: 100 },
    { navn: 'To Øl Easy Pilsner 6x33cl', soeg: [], pris: 50 },
    { navn: 'Anarkis New England IPA 6-pak', soeg: [], pris: 80 },
    { navn: 'Ølmarked 12x25cl/12x33cl', soeg: [], pris: 88 },
    { navn: 'To Øl Snuble Juice eller Whirl Domination IPA 6x33cl', soeg: [], pris: 80 },
    { navn: 'Ølmarked 15x33cl/18x33cl', soeg: [], pris: 79 },
    { navn: 'Carlsberg, Grøn Tuborg eller Tuborg Classic flasker 30x33cl', soeg: [], pris: 140 },
    { navn: 'Ølmarked 18x33cl', soeg: [], pris: 75 },
    { navn: 'Alkoholfri ølmarked 33cl', soeg: [], pris: 12 },
    { navn: 'To Øl Implosion Lager 0.3% 6x33cl', soeg: [], pris: 50 },
    { navn: 'Amager Bryghus, Brooklyn, Mikkeller, Frejdahl, Erdinger, Fynsk Fri eller Anarkist 33-50cl', soeg: [], pris: 20 },
    { navn: 'Carlsberg Nordic, Tuborg, Heineken eller Royal 6x33cl', soeg: [], pris: 37 },
    { navn: 'Alkoholfri ølmarked 33cl ds.', soeg: [], pris: 10 },

    { navn: 'Amper Energy 50cl', soeg: [], pris: 6 },
    { navn: 'Økologisk ingefærshot 50cl', soeg: [], pris: 25 },
    { navn: 'Økologisk sodavand 1 liter', soeg: [], pris: 13 },
    { navn: 'Æblemost 75cl', soeg: [], pris: 20 },
    { navn: 'Pure vitamin- eller hydration drik 50cl', soeg: [], pris: 7 },
    { navn: 'Økologisk bland selv drik 50cl', soeg: [], pris: 26 },

    { navn: 'Boble Lagune Rosé 75cl', soeg: [], pris: 199 },
    { navn: 'La Belle Angele 75cl', soeg: [], pris: 50 },
    { navn: 'Lyv 75cl', soeg: [], pris: 65 },
    { navn: 'Dr. Pauly Noble House 75cl', soeg: [], pris: 45 },
    { navn: 'Kim Crawford Pinot Noir 75cl', soeg: [], pris: 95 },
    { navn: 'Selaks 75cl', soeg: [], pris: 59 },
    { navn: 'Rabl Grüner Veltliner eller Riesling 75cl', soeg: [], pris: 75 },
    { navn: 'Kim Crawford Small Parcels 75cl', soeg: [], pris: 135 },

    { navn: 'Afskårne blomster eller buket', soeg: [], pris: 79 },
    { navn: 'Grøn plante 3 stk.', soeg: [], pris: 60 },
    { navn: 'Mini blomster', soeg: [], pris: 6 },
    { navn: 'Orkidé', soeg: [], pris: 59 },
    { navn: 'Spansk marguerit 11cm', soeg: [], pris: 12 },
    { navn: 'Hortensia 21cm', soeg: [], pris: 99 },
    { navn: 'Marseille fletkurv', soeg: [], pris: 89 },
    { navn: 'Prydgræs 19cm', soeg: [], pris: 50 },
    { navn: 'Eksklusive pelargonier 12cm', soeg: [], pris: 25 },

    { navn: 'Apple iPad 11” Wi-Fi 128GB', soeg: [], pris: 2649 },
    { navn: 'Apple AirPods Pro 3', soeg: [], pris: 1699 },
    { navn: '43FA7025 TV 43”', soeg: [], pris: 1588 },
    { navn: 'Targus iPad 10,9” click-in cover', soeg: [], pris: 199 },
    { navn: 'Ledningsfri støvsuger', soeg: [], pris: 699 },
    { navn: 'Støvsuger', soeg: [], pris: 599 },
    { navn: 'OnePlus Nord CE5 8/128GB', soeg: [], pris: 1499 },
    { navn: 'HP Envy 6120e AIO', soeg: [], pris: 449 },

    { navn: 'Samsung TU55U7025F 55” TV', soeg: [], pris: 2999 },
    { navn: 'Samsung TQ55S85F 55” OLED TV', soeg: [], pris: 6555 },
    { navn: 'Philips 65PUS8000 65” TV', soeg: [], pris: 3666 },
    { navn: 'Hisense 58A6N 58” TV', soeg: [], pris: 2400 },

    { navn: 'Spiloppe juniorseng', soeg: [], pris: 2100 },
    { navn: 'Spiloppe halvhøj seng', soeg: [], pris: 2150 },
    { navn: 'Kaya juniorseng', soeg: [], pris: 2250 },
    { navn: 'Spiloppe juniorseng med udtræksseng', soeg: [], pris: 3600 },
    { navn: 'Spiloppe juniorseng 90x200cm', soeg: [], pris: 2650 },
    { navn: 'Spiloppe halvhøj seng med rutsjebane', soeg: [], pris: 3700 },

    { navn: 'New York havebord', soeg: [], pris: 1999.2 },
    { navn: 'Lindholdt havestol', soeg: [], pris: 159.2 },
    { navn: 'New York havebord med 6 Lindholdt havestole', soeg: [], pris: 2954.4 },
    { navn: 'Lugo havemøbelsæt', soeg: [], pris: 4474.4 },
    { navn: 'Lugo havebord', soeg: [], pris: 1599.2 },
    { navn: 'Lugo havestol', soeg: [], pris: 479.2 },
    { navn: 'Turtle 3.0 pizzaovn', soeg: [], pris: 999 },
    { navn: 'Weber Q2800N gasgrill', soeg: [], pris: 2999 },
    { navn: 'Stiga Multiclip 47 S plæneklipper', soeg: [], pris: 1999 },
    { navn: 'Grouw Pure vision robotplæneklipper', soeg: [], pris: 3999 },

    { navn: 'SBS powerbank 10.000 mAh', soeg: [], pris: 129 },
    { navn: 'PS5 spil', soeg: [], pris: 299 },
    { navn: 'PS-1000B Party højttaler', soeg: [], pris: 679 },
    { navn: 'PS-2000B Party højttaler', soeg: [], pris: 879 },
    { navn: 'HW-B66CF soundbar med subwoofer', soeg: [], pris: 1999 },

    { navn: 'Tefal Daily stålgryde eller pande', soeg: [], pris: 149 },
    { navn: 'Smartstore Classic sampak 14L', soeg: [], pris: 69 },
    { navn: 'Smartstore Classic sampak 31L', soeg: [], pris: 129 },
    { navn: 'Britt Andersen Læsø airfryer med skillevæg', soeg: [], pris: 799 },
    { navn: 'Kølende Ergoflow hovedpude', soeg: [], pris: 200 },
    { navn: 'Kølende sommerdyne', soeg: [], pris: 300 },
    { navn: 'Huma Prestige boxmadras 90x200cm', soeg: [], pris: 3650 },

    { navn: 'Køletaske 18 liter', soeg: [], pris: 179 },
    { navn: 'Classic dobbelt luftmadras', soeg: [], pris: 78 },
    { navn: 'Køletaske 20 liter', soeg: [], pris: 129 },
    { navn: 'Classic single luftmadras', soeg: [], pris: 48 },
    { navn: 'TDW60 køleboks med kompressor', soeg: [], pris: 2599 },
    { navn: 'Pop-Up 2 telt', soeg: [], pris: 249 },
    { navn: 'Festivaltelt', soeg: [], pris: 69 },
    { navn: 'CR65X køle-/fryseskab', soeg: [], pris: 2699 },
    { navn: 'Trolley', soeg: [], pris: 149 },
    { navn: 'Basic 250 sovepose', soeg: [], pris: 99 },
    { navn: 'Mini Pro 50 sovepose', soeg: [], pris: 99 },
    { navn: 'Indkøbstrolley', soeg: [], pris: 149 },
    { navn: 'CX30 køleboks med kompressor', soeg: [], pris: 1499 },

    { navn: 'Robotstøvsuger Dreame L40 Ultra AE', soeg: [], pris: 2999 },
    { navn: 'Robotstøvsuger L50 Ultra AE', soeg: [], pris: 4699 },
    { navn: 'Eltandbørste Vitality Pro', soeg: [], pris: 199 },
    { navn: 'Kropstrimmer eller skægtrimmer', soeg: [], pris: 249 },

    { navn: 'Philips trådløse on-ear', soeg: [], pris: 349 },
    { navn: 'Tapo C210 Pan/tilt sikkerhedskamera', soeg: [], pris: 249 },
    { navn: 'TP-Link Tapo C500 overvågningskamera', soeg: [], pris: 189 },
    { navn: 'Norton 360 Deluxe 5 enheder', soeg: [], pris: 149 },
    { navn: 'SanDisk 64GB Ultra microSDXC eller USB 3.0 flash drive', soeg: [], pris: 119 },
    { navn: 'Instax mini link 3 printer', soeg: [], pris: 799 },

    { navn: 'Ovn TU5AB10SCK', soeg: [], pris: 2699 },
    { navn: 'Induktionskogeplade HOI630MX', soeg: [], pris: 2999 },
    { navn: 'Køleskab med fryseboks WKB179W', soeg: [], pris: 1999 },
    { navn: 'Opvaskemaskine BDUN26645W', soeg: [], pris: 2699 },
    { navn: 'Køle-fryseskab 31FK4186-1', soeg: [], pris: 2999 },
    { navn: 'Vaskemaskine WW11DG5B25TEEE', soeg: [], pris: 3333 },

    { navn: 'K18 køleboks med kompressor', soeg: [], pris: 1399 },
    { navn: 'Køleboks 40 liter', soeg: [], pris: 799 },
    { navn: 'Festivalstol sort', soeg: [], pris: 35 },
    { navn: 'Køletaske 20 liter', soeg: [], pris: 50 },
    { navn: 'Køletaske 14 liter', soeg: [], pris: 40 },
    { navn: 'Texas Razor 4651 TR/WE plæneklipper', soeg: [], pris: 2299 },
    { navn: 'Festivalstol rød', soeg: [], pris: 40 },
    { navn: 'Nexgrill Deluxe 3 gasgrill', soeg: [], pris: 2499 },
    { navn: 'Off Road trækvogn', soeg: [], pris: 249 },
    { navn: 'Blomster 10,5-13cm', soeg: [], pris: 30 },
    { navn: 'Stauder 19cm', soeg: [], pris: 60 },
    { navn: 'Areca eller Strelitzia Nicolai 24cm', soeg: [], pris: 299 },

    { navn: 'Nederdel', soeg: [], pris: 79 },
    { navn: 'Denimshorts børn', soeg: [], pris: 129 },
    { navn: 'Bøllehat børn', soeg: [], pris: 49 },
    { navn: 'T-shirt børn', soeg: [], pris: 99 },
    { navn: 'Denimshorts børn 2 stk.', soeg: [], pris: 69 },
    { navn: 'Sandal børn', soeg: [], pris: 149 },
    { navn: 'Kjole børn', soeg: [], pris: 99 },
    { navn: 'Taske', soeg: [], pris: 59 },
    { navn: 'Sandal børn frit valg', soeg: [], pris: 149 },

    { navn: 'Stråhat', soeg: [], pris: 69 },
    { navn: 'Kjole dame', soeg: [], pris: 129 },
    { navn: 'Kjole dame premium', soeg: [], pris: 349 },
    { navn: 'T-shirt eller top 2 stk.', soeg: [], pris: 99 },
    { navn: 'Kjole dame tilbud', soeg: [], pris: 249 },
    { navn: 'Top dame', soeg: [], pris: 179 },
    { navn: 'Strømper til dame 5-pak', soeg: [], pris: 49 },
    { navn: 'Vest dame', soeg: [], pris: 179 },
    { navn: 'Shorts dame', soeg: [], pris: 149 },
    { navn: 'Glimmerstrømper', soeg: [], pris: 20 },
    { navn: 'Sneakers dame', soeg: [], pris: 199 },

    { navn: 'Bh Romance 2 stk.', soeg: [], pris: 249 },
    { navn: 'Trusser Romance 2 pakker', soeg: [], pris: 249 },
    { navn: 'Tights 2 stk.', soeg: [], pris: 129 },
    { navn: 'Undertrøje eller trusser 3 stk.', soeg: [], pris: 249 },
    { navn: 'T-shirt, undertrøje eller trusser 3 stk.', soeg: [], pris: 169 },
    { navn: 'Trusser 3 par', soeg: [], pris: 249 },
    { navn: 'Undertrøje eller 2-pak trusser 3 stk.', soeg: [], pris: 79 },
    { navn: 'Tights 5-pak', soeg: [], pris: 99 },

    { navn: 'Kasket', soeg: [], pris: 79 },
    { navn: 'T-shirt ensfarvet eller print med flag', soeg: [], pris: 49 },
    { navn: 'Tanktop', soeg: [], pris: 69 },
    { navn: 'Shorts dame/herre', soeg: [], pris: 129 },
    { navn: 'Shorts herre', soeg: [], pris: 149 },
    { navn: 'T-shirt børn DBU', soeg: [], pris: 59 },
    { navn: 'Kjole børn DBU', soeg: [], pris: 79 },
    { navn: 'Tørklæde', soeg: [], pris: 79 },
    { navn: 'Denimshorts børn DBU', soeg: [], pris: 129 },
    { navn: 'Bøllehat DBU', soeg: [], pris: 49 },
    { navn: 'Strømper DBU', soeg: [], pris: 20 },

    { navn: 'T-shirt S-4XL', soeg: [], pris: 69 },
    { navn: 'T-shirt S-3XL', soeg: [], pris: 79 },
    { navn: 'LEGO VM fodbold', soeg: [], pris: 269 },
    { navn: 'Slippers', soeg: [], pris: 59 },
    { navn: 'Jeans 2 par', soeg: [], pris: 379 },
    { navn: 'Shorts S-5XL', soeg: [], pris: 199 },
    { navn: 'Clogs voksen', soeg: [], pris: 69 },
    { navn: 'Clogs børn', soeg: [], pris: 59 },
    { navn: 'T-shirt S-4XL hvid', soeg: [], pris: 69 },
    { navn: 'Fodboldsæt 98-152cm', soeg: [], pris: 99 },
    { navn: 'T-shirt S-3XL rød', soeg: [], pris: 79 },
    { navn: 'T-shirt S-4XL rød', soeg: [], pris: 69 },
    { navn: 'Fodboldstrømper 26-41', soeg: [], pris: 49 },
  ],
};
