// Opskriftsbog — organiseret efter kødkategori
// AI'en filtrerer automatisk baseret på brugerens kødpræferencer

export const OPSKRIFTER = [
  // ===== SUPPER =====
  {
    id: "tomatsuppe",
    kategorier: ["suppe"],
    minutter: 45,
    navn: "Tomatsuppe med pasta",
    kategori: "aftensmad",
    koed: "Alt",
    portioner: 4,
    ingredienser: [
      { navn: "Løg", maengde: "1 stk (ca. 100 g)", soeg: ["løg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Hvidløg", maengde: "1 fed", soeg: ["hvidløg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Gulerødder", maengde: "3 stk (ca. 175 g)", soeg: ["gulerødder", "gulerodder"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Hakkede tomater", maengde: "1 dåse (400 g)", soeg: ["hakkede tomater", "dåsetomater", "tomat"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 8 },
      { navn: "Pasta (minisuppehorn)", maengde: "200 g", soeg: ["pasta", "suppehorn"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Smør", maengde: "25 g", soeg: ["smør", "smørbar"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Grøntsagsbouillon", maengde: "1 liter", soeg: ["bouillon"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 5 },
      { navn: "Sukker", maengde: "1 tsk", soeg: ["sukker"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 0 },
      { navn: "Tørret basilikum", maengde: "1 tsk", soeg: [], estimeret: true, estimereretPris: 0 },
      { navn: "Salt og peber", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Smelt smørret i en stor gryde og svits løg, hvidløg, salt og sukker i ca. 2 min uden at det bruner",
      "Tilsæt gulerødder, hakkede tomater, basilikum og bouillon, og kog under låg ved svag varme i ca. 20 min, til gulerødderne er møre",
      "Blend suppen glat og bring den i kog igen",
      "Tilsæt pasta og kog videre under låg i ca. 10 min, til pastaen er mør",
      "Smag til og server, evt. med en klat fraiche og brød",
    ]
  },
  {
    id: "kartoffelsuppe",
    kategorier: ["suppe"],
    minutter: 30,
    navn: "Cremet kartoffelsuppe med porre",
    kategori: "aftensmad",
    koed: "Alt",
    portioner: 4,
    ingredienser: [
      { navn: "Kartofler", maengde: "1 kg", soeg: ["kartofler"], vaelgBilligstPerKg: true, estimeret: false },
      { navn: "Porre", maengde: "3 stk", soeg: ["porre", "porrer"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 12 },
      { navn: "Grøntsagsbouillon", maengde: "1,2 liter", soeg: ["bouillon"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 5 },
      { navn: "Piskefløde", maengde: "½ dl", soeg: ["piskefløde", "fløde"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Rugbrød (til topping)", maengde: "3 skiver", soeg: ["rugbrød", "rugbroed"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Bacon (valgfri topping)", maengde: "3 skiver", soeg: ["bacon"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 10 },
      { navn: "Olivenolie", maengde: "1 spsk", soeg: [], estimeret: true, estimereretPris: 0 },
      { navn: "Salt og peber", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Sauter kartofler og porre i olivenolie i et par minutter under omrøring",
      "Tilsæt bouillon, læg låg på og kog i ca. 20 min, til kartoflerne er møre",
      "Blend suppen med piskefløden, til den er cremet — juster med lidt mere bouillon hvis nødvendigt",
      "Smag til med salt og peber",
      "Server med ristet rugbrød i tern og sprødristet bacon (bacon kan udelades)",
    ]
  },
  {
    id: "hoensekoedssuppe",
    kategorier: ["suppe"],
    minutter: 90,
    navn: "Gammeldags hønsekødssuppe",
    kategori: "aftensmad",
    koed: "Kylling",
    portioner: 4,
    ingredienser: [
      { navn: "Hel kylling", maengde: "1 stk (ca. 1,5 kg)", soeg: ["kylling", "kyllingebryst", "kyllingelår"], vaelgBilligstPerKg: true, estimeret: false },
      { navn: "Gulerødder", maengde: "6 stk", soeg: ["gulerødder", "gulerodder"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Porre", maengde: "3 stk", soeg: ["porre", "porrer"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 12 },
      { navn: "Løg", maengde: "1 stk", soeg: ["løg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Knoldselleri", maengde: "½ stk", soeg: [], estimeret: true, estimereretPris: 10 },
      { navn: "Persillerødder", maengde: "3 stk", soeg: [], estimeret: true, estimereretPris: 8 },
      { navn: "Kalvefond", maengde: "2½ dl", soeg: [], estimeret: true, estimereretPris: 12 },
      { navn: "Krydderurter (laurbær, timian, persille, peberkorn)", maengde: "efter smag", soeg: [], estimeret: true, estimereretPris: 0 },
      { navn: "Salt og peber", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Skyl kyllingen og læg den i en stor gryde. Hæld vand på, bring i kog og skum urenheder fra",
      "Tilsæt løg, kalvefond og krydderurterne (bind dem evt. sammen) og kog ved svag varme i ca. 1½ time",
      "Skræl og skær gulerødder, persillerødder og knoldselleri i tern, og skær porren i skiver",
      "Tag kyllingen op, lad den køle lidt af, og pluk kødet af benene",
      "Kog grøntsagerne møre i suppen, ca. 10-15 min",
      "Kom kødet tilbage i gryden, smag til med salt og peber og server — evt. med kød- og melboller",
    ]
  },

  // ===== SALATER =====
  {
    id: "graesk-salat",
    kategorier: ["salat"],
    minutter: 15,
    navn: "Græsk salat med feta og oliven",
    kategori: "aftensmad",
    koed: "Alt",
    portioner: 4,
    ingredienser: [
      { navn: "Tomater", maengde: "250 g", soeg: ["tomat", "cherrytomater"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 12 },
      { navn: "Agurk", maengde: "1 stk", soeg: ["agurk"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 8 },
      { navn: "Peberfrugt", maengde: "1 stk", soeg: ["peberfrugt"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Rødløg", maengde: "1 stk", soeg: ["løg", "rødløg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Feta/salatost", maengde: "100 g", soeg: ["ost", "salatost", "feta"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 12 },
      { navn: "Oliven", maengde: "50 g", soeg: ["oliven"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 12 },
      { navn: "Olie- og eddikedressing (olivenolie, hvidvinseddike, honning, sennep, oregano)", maengde: "til dressing", soeg: [], estimeret: true, estimereretPris: 3 },
      { navn: "Salt og peber", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Halver tomaterne og kom dem i en stor skål",
      "Halver agurken, skrab kernerne ud og skær den i skiver — kom den i skålen med peberfrugt i strimler og rødløg i tynde både",
      "Pisk olivenolie, eddike, honning, sennep og oregano sammen og smag til med salt og peber",
      "Hæld dressingen over salaten og vend forsigtigt rundt",
      "Pynt med feta og oliven og lad salaten trække på køl til servering",
    ]
  },
  {
    id: "gron-salat-basilikum",
    kategorier: ["salat"],
    minutter: 15,
    navn: "Grøn salat med basilikum-vinaigrette",
    kategori: "aftensmad",
    koed: "Alt",
    portioner: 4,
    ingredienser: [
      { navn: "Babysalatblade", maengde: "100 g", soeg: ["salat", "babysalat"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 12 },
      { navn: "Rucolasalat", maengde: "100 g", soeg: ["salat", "rucola"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 12 },
      { navn: "Rødløg", maengde: "1 stk", soeg: ["løg", "rødløg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Ristede pinjekerner", maengde: "30 g", soeg: ["pinjekerner"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 15 },
      { navn: "Basilikum-vinaigrette (olivenolie, hvidvinseddike, hvidløg, honning, citron, basilikum)", maengde: "til dressing", soeg: [], estimeret: true, estimereretPris: 5 },
      { navn: "Salt og peber", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Blend olivenolie, eddike, hvidløg, honning, salt, peber, citronsaft og basilikum til en ensartet, grøn vinaigrette og smag til",
      "Vend salatblade, rødløg og pinjekerner sammen med vinaigretten og server",
    ]
  },
  {
    id: "burrata-salat",
    kategorier: ["salat"],
    minutter: 10,
    navn: "Burrata-salat med tomat",
    kategori: "aftensmad",
    koed: "Alt",
    portioner: 4,
    ingredienser: [
      { navn: "Mix cherrytomater", maengde: "250 g", soeg: ["tomat", "cherrytomater"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 12 },
      { navn: "Rødløg", maengde: "¼ stk", soeg: ["løg", "rødløg"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 2 },
      { navn: "Babysalatblade", maengde: "2 dl", soeg: ["salat", "babysalat"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 10 },
      { navn: "Burrata ost", maengde: "1 stk", soeg: ["ost", "burrata"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 20 },
      { navn: "Basilikum", maengde: "½ dl blade", soeg: [], estimeret: true, estimereretPris: 0 },
      { navn: "Balsamico glaze", maengde: "1 spsk", soeg: [], estimeret: true, estimereretPris: 0 },
      { navn: "Salt og peber", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Skær tomaterne i halve og rødløget i meget tynde både",
      "Bland salatblade og basilikum med tomater og løg og anret på et fad",
      "Kom burrataen på toppen og dryp med balsamico glaze",
      "Drys med salt og peber og server",
    ]
  },
  {
    id: "sommersalat-jordbaer",
    kategorier: ["salat"],
    minutter: 30,
    navn: "Sommersalat med jordbær",
    kategori: "aftensmad",
    koed: "Alt",
    portioner: 4,
    ingredienser: [
      { navn: "Rucolasalat", maengde: "100 g", soeg: ["salat", "rucola"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 12 },
      { navn: "Babyspinat", maengde: "100 g", soeg: ["spinat"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Friske ærter", maengde: "200 g", soeg: ["ærter"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 15 },
      { navn: "Cherrytomater", maengde: "400 g", soeg: ["tomat", "cherrytomater"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 18 },
      { navn: "Jordbær", maengde: "250 g", soeg: ["jordbær"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 15 },
      { navn: "Forårsløg", maengde: "1 bundt (ca. 100 g)", soeg: ["løg", "forårsløg"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 8 },
      { navn: "Salatost", maengde: "200 g", soeg: ["ost", "salatost", "feta"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 20 },
      { navn: "Dressing (olivenolie, hvid balsamico, citron, sennep)", maengde: "til dressing", soeg: [], estimeret: true, estimereretPris: 0 },
      { navn: "Salt og peber", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Læg salat, spinat, ærter, tomater, jordbær og forårsløg lagvis i et stort fad",
      "Fordel salatosten på toppen",
      "Pisk olie, balsamico, citronsaft, sennep, salt og peber sammen til en dressing og smag til",
      "Fordel dressingen over salaten og server",
    ]
  },
  {
    id: "coleslaw",
    kategorier: ["salat"],
    minutter: 20,
    navn: "Coleslaw med hvidkål og gulerødder",
    kategori: "aftensmad",
    koed: "Alt",
    portioner: 4,
    ingredienser: [
      { navn: "Hvidkål", maengde: "500 g", soeg: ["hvidkål"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 12 },
      { navn: "Gulerødder", maengde: "6 stk (ca. 500 g)", soeg: ["gulerødder", "gulerodder"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Crème fraiche", maengde: "2 dl", soeg: ["creme fraiche"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Mayonnaise", maengde: "1 dl", soeg: ["mayonnaise"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 12 },
      { navn: "Sukker", maengde: "2 tsk", soeg: ["sukker"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 0 },
      { navn: "Dijonsennep og citronsaft", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
      { navn: "Salt og peber", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Rør crème fraiche sammen med mayonnaise, sukker, sennep, citronsaft, salt og peber i en stor skål",
      "Vend fintsnittet hvidkål og groftrevne gulerødder i dressingen og smag til",
      "Top evt. med hakket persille og stil på køl til servering",
    ]
  },
  {
    id: "vandmelonsalat",
    kategorier: ["salat"],
    minutter: 15,
    navn: "Vandmelonsalat med salatost",
    kategori: "aftensmad",
    koed: "Alt",
    portioner: 4,
    ingredienser: [
      { navn: "Vandmelon", maengde: "1 lille (ca. 1 kg)", soeg: ["vandmelon"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 25 },
      { navn: "Salatost", maengde: "300 g", soeg: ["ost", "salatost", "feta"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 25 },
      { navn: "Græskarkerner", maengde: "½ dl", soeg: [], estimeret: true, estimereretPris: 8 },
      { navn: "Balsamicosirup (balsamicoeddike og sukker)", maengde: "til pynt", soeg: ["sukker"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 5 },
      { navn: "Mynteblade", maengde: "til pynt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Kog balsamicoeddike og sukker ved kraftig varme i ca. 1 min til en sirup, og lad den køle af",
      "Rist græskarkernerne på en tør pande i ca. 2 min og lad dem køle af",
      "Anret vandmelon- og ostetern i et fladt fad og dryp lidt sirup over",
      "Drys med græskarkerner, pynt med mynteblade og server resten af siruppen ved siden af",
    ]
  },
  {
    id: "tomatsalat-mozzarella",
    kategorier: ["salat"],
    minutter: 20,
    navn: "Tomatsalat med mozzarella og rødløg",
    kategori: "aftensmad",
    koed: "Alt",
    portioner: 2,
    ingredienser: [
      { navn: "Tomater", maengde: "3 stk", soeg: ["tomat"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 10 },
      { navn: "Rødløg", maengde: "1 lille", soeg: ["løg", "rødløg"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 2 },
      { navn: "Frisk mozzarella", maengde: "125 g (1 kugle)", soeg: ["ost", "mozzarella"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 15 },
      { navn: "Basilikum", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
      { navn: "Dressing (balsamico og olivenolie)", maengde: "til dressing", soeg: [], estimeret: true, estimereretPris: 0 },
      { navn: "Salt og peber", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Skær tomater og mozzarella i skiver og læg dem skiftevis på et fad",
      "Hak rødløget fint og drys det over, og fordel friske basilikumblade",
      "Bland en dressing af balsamico og olivenolie og smag til med salt og peber",
      "Hæld dressingen over lige før servering, eller server den ved siden af",
    ]
  },
  {
    id: "spidskaalssalat",
    kategorier: ["salat"],
    minutter: 15,
    navn: "Spidskålssalat med æble og avocado",
    kategori: "aftensmad",
    koed: "Alt",
    portioner: 4,
    ingredienser: [
      { navn: "Spidskål", maengde: "½ stk, fintsnittet", soeg: ["spidskål"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 8 },
      { navn: "Æble", maengde: "1 stk", soeg: ["æble"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 4 },
      { navn: "Avocado", maengde: "1 stk", soeg: ["avocado"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 14 },
      { navn: "Pinjekerner", maengde: "50 g", soeg: ["pinjekerner"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 20 },
      { navn: "Agurk", maengde: "½ stk", soeg: ["agurk"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 4 },
      { navn: "Dressing (citron, dijonsennep, persille)", maengde: "til dressing", soeg: [], estimeret: true, estimereretPris: 3 },
      { navn: "Salt og peber", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Rist pinjekernerne på en tør pande i 2-3 min til de er gyldenbrune",
      "Blend agurk, citron, ½ avocado, dijonsennep og persille til en cremet dressing og smag til med salt og peber",
      "Vend fintsnittet spidskål grundigt med dressingen",
      "Anret med avocado i tern, æblestykker og ristede pinjekerner og kværn peber over inden servering",
    ]
  },
  {
    id: "broccolisalat",
    kategorier: ["salat"],
    minutter: 10,
    navn: "Broccolisalat med bacon og tranebær",
    kategori: "aftensmad",
    koed: "Alt",
    portioner: 4,
    ingredienser: [
      { navn: "Broccoli", maengde: "1 stk", soeg: ["broccoli"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 12 },
      { navn: "Bacon", maengde: "50 g", soeg: ["bacon"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Rødløg", maengde: "½ stk", soeg: ["løg", "rødløg"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 2 },
      { navn: "Granatæblekerner", maengde: "½ dl", soeg: [], estimeret: true, estimereretPris: 10 },
      { navn: "Solsikkekerner", maengde: "2 spsk", soeg: [], estimeret: true, estimereretPris: 3 },
      { navn: "Tørrede tranebær", maengde: "2 spsk", soeg: [], estimeret: true, estimereretPris: 5 },
      { navn: "Crème fraiche 18 %", maengde: "1 dl", soeg: ["creme fraiche"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Mayonnaise", maengde: "2 spsk", soeg: ["mayonnaise"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 5 },
      { navn: "Sukker", maengde: "1 tsk", soeg: ["sukker"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 0 },
      { navn: "Salt og peber", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Steg bacon sprødt på panden, lad det dryppe af og hak det groft",
      "Rør dressingen sammen af crème fraiche, mayonnaise, sukker, salt og peber og smag til",
      "Vend broccoli i små buketter, rødløg, granatæble, solsikkekerner, tranebær og bacon med dressingen",
      "Tag evt. lidt broccoli, bacon og granatæble fra til topping og server",
    ]
  },

  // ===== AFTENSMAD =====
  {
    id: "lasagnette",
    kategorier: [],
    minutter: 60,
    navn: "Lasagnette",
    kategori: "aftensmad",
    koed: "Oksekød",
    portioner: 4,
    ingredienser: [
      { navn: "Hakket oksekød", maengde: "400 g", soeg: ["hakket oksekød", "hakket dansk oksekød"], vaelgBilligstPerKg: true, estimeret: false },
      { navn: "Løg", maengde: "1 stk", soeg: ["løg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Hvidløg", maengde: "3 fed", soeg: ["hvidløg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Gulerødder", maengde: "3 stk", soeg: ["gulerødder", "gulerodder"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Bladselleri", maengde: "3 stængler", soeg: [], estimeret: true, estimereretPris: 8 },
      { navn: "Hakkede tomater", maengde: "800 g (2 dåser)", soeg: ["hakkede tomater", "dåsetomater", "tomat"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 16 },
      { navn: "Tomatpuré", maengde: "25 g", soeg: ["tomatpuré", "tomatpure"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 4 },
      { navn: "Mælk", maengde: "2 dl", soeg: ["mælk"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 3 },
      { navn: "Pasta (mafalda corta)", maengde: "200 g", soeg: ["pasta"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Frisk mozzarella", maengde: "125 g", soeg: ["ost", "mozzarella"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 15 },
      { navn: "Grøntsagsbouillon", maengde: "2 dl", soeg: ["bouillon"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 3 },
      { navn: "Krydderier (oregano, timian, basilikum) og olie", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Sauter løg og hvidløg i olie til de er bløde, skru op og brun kødet godt af",
      "Rør majsstivelse ud i mælken og kom det i sammen med tomater, tomatpuré, bouillon, gulerødder, selleri og krydderier",
      "Lad saucen simre 5 min og smag til med salt og peber",
      "Rør pastaen i, kom det hele i et smurt ovnfast fad og fordel mozzarella i mindre stykker over",
      "Bag ved 175° varmluft i ca. 25 min, til pastaen er mør med lidt bid",
    ]
  },
  {
    id: "morbradgryde",
    kategorier: [],
    minutter: 30,
    navn: "Mørbradgryde",
    kategori: "aftensmad",
    koed: "Svinekød",
    portioner: 4,
    ingredienser: [
      { navn: "Svinemørbrad", maengde: "400 g", soeg: ["svinekød", "svinemørbrad", "mørbrad"], vaelgBilligstPerKg: true, estimeret: false },
      { navn: "Bacon", maengde: "150 g", soeg: ["bacon"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Champignon", maengde: "400 g", soeg: ["champignon"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 15 },
      { navn: "Løg", maengde: "2 stk", soeg: ["løg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Hvidløg", maengde: "2 fed", soeg: ["hvidløg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Hakkede tomater", maengde: "1 dåse (400 g)", soeg: ["hakkede tomater", "tomat"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 8 },
      { navn: "Piskefløde", maengde: "3 dl", soeg: ["piskefløde", "fløde"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Gulerødder", maengde: "3 stk", soeg: ["gulerødder", "gulerodder"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Cocktailpølser", maengde: "200 g", soeg: ["pølser"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 15 },
      { navn: "Tomatpuré", maengde: "2 spsk", soeg: ["tomatpuré", "tomatpure"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 4 },
      { navn: "Ris", maengde: "6 dl", soeg: ["ris"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 17 },
      { navn: "Krydderier (paprika, timian) og salt", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Steg bacontern gyldne i en stor gryde, tilsæt mørbradstykker og brun dem ved kraftig varme ca. 5 min",
      "Tilsæt løg, hvidløg, champignon, tomatpuré og krydderier og steg ca. 3 min",
      "Tilsæt hakkede tomater, fløde, lidt vand og gulerødder, og kog under låg ved svag varme ca. 15 min",
      "Kom cocktailpølser i, varm igennem, smag til og server med nykogte ris",
    ]
  },
  {
    id: "frikadeller",
    kategorier: [],
    minutter: 45,
    navn: "Frikadeller",
    kategori: "aftensmad",
    koed: "Svinekød",
    portioner: 4,
    ingredienser: [
      { navn: "Hakket svinekød", maengde: "500 g", soeg: ["hakket grisekød", "hakket svinekød", "svinekød"], vaelgBilligstPerKg: true, estimeret: false },
      { navn: "Løg", maengde: "1 stk", soeg: ["løg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Hvidløg", maengde: "1 fed", soeg: ["hvidløg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Hvedemel", maengde: "2 spsk", soeg: ["hvedemel"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 0 },
      { navn: "Havregryn", maengde: "2 spsk", soeg: ["havregryn"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 0 },
      { navn: "Mælk", maengde: "1 dl", soeg: ["mælk"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 2 },
      { navn: "Æg", maengde: "1-2 stk", soeg: ["æg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Smør og olie til stegning", maengde: "lidt", soeg: ["smør", "smørbar"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 0 },
      { navn: "Krydderier (timian, spidskommen) og salt", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Rør alle ingredienserne til farsen sammen i 2-3 min med håndmikser",
      "Lad farsen hvile mindst ½ time på køl",
      "Form frikadellerne og steg dem i smør og olie ved middelvarme ca. 5 min på hver side til de er gennemstegte",
    ]
  },
  {
    id: "spaghetti-kodsovs",
    kategorier: [],
    minutter: 80,
    navn: "Spaghetti med kødsovs",
    kategori: "aftensmad",
    koed: "Oksekød",
    portioner: 4,
    ingredienser: [
      { navn: "Hakket oksekød", maengde: "400 g", soeg: ["hakket oksekød", "hakket dansk oksekød"], vaelgBilligstPerKg: true, estimeret: false },
      { navn: "Bacon", maengde: "100 g", soeg: ["bacon"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Løg", maengde: "2 små", soeg: ["løg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Hvidløg", maengde: "3 fed", soeg: ["hvidløg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Gulerødder", maengde: "2 stk", soeg: ["gulerødder", "gulerodder"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Bladselleri", maengde: "2-3 stængler", soeg: [], estimeret: true, estimereretPris: 6 },
      { navn: "Hakkede tomater", maengde: "2 dåser (800 g)", soeg: ["hakkede tomater", "tomat"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 16 },
      { navn: "Tomatpuré", maengde: "1 dåse", soeg: ["tomatpuré", "tomatpure"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 5 },
      { navn: "Oksebouillon", maengde: "1-2 dl", soeg: ["bouillon"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 3 },
      { navn: "Spaghetti", maengde: "400 g", soeg: ["pasta", "spaghetti"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Parmesan", maengde: "50 g", soeg: ["ost", "parmesan"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 12 },
      { navn: "Timian, salt og peber", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Steg bacon sprødt, tag det op, og sauter løg, hvidløg og timian i baconfedtet til løgene er bløde",
      "Tilsæt kødet og brun det godt af",
      "Tilsæt finthakket gulerod, selleri og tomatpuré og svits ca. 3 min",
      "Tilsæt hakkede tomater og bacon og lad simre under låg ved lav varme ca. 1 time — tilsæt lidt bouillon undervejs",
      "Smag til med salt og peber, kog spaghetti og server med revet parmesan",
    ]
  },
  {
    id: "boller-i-karry",
    kategorier: [],
    minutter: 45,
    navn: "Boller i karry",
    kategori: "aftensmad",
    koed: "Svinekød",
    portioner: 4,
    ingredienser: [
      { navn: "Hakket grise- og kalvekød", maengde: "300 g", soeg: ["hakket grisekød", "hakket kalvekød", "svinekød"], vaelgBilligstPerKg: true, estimeret: false },
      { navn: "Løg", maengde: "2 stk", soeg: ["løg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Hvidløg", maengde: "4 fed", soeg: ["hvidløg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Æg", maengde: "1 stk", soeg: ["æg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Hvedemel", maengde: "4 spsk", soeg: ["hvedemel"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 0 },
      { navn: "Mælk", maengde: "3 dl", soeg: ["mælk"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 5 },
      { navn: "Smør og karry", maengde: "lidt", soeg: ["smør", "smørbar"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 3 },
      { navn: "Æble", maengde: "1 stk", soeg: ["æble"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 4 },
      { navn: "Ris", maengde: "4 dl", soeg: ["ris"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 12 },
      { navn: "Salat (romaine, æble, slikærter, løg)", maengde: "til servering", soeg: [], estimeret: true, estimereretPris: 15 },
      { navn: "Salt og peber", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Rør farsen af kød, salt, løg, peber, æg og mel, og rør mælken i lidt efter lidt",
      "Form boller med en ske og kog dem i letsaltet vand ca. 8 min — gem ca. 6 dl kogevand til saucen",
      "Smelt smør, svits løg, drys karry over og svits 1 min, drys mel og bouillon-pulver i",
      "Pisk siet kogevand og mælk i og kog saucen ved svag varme ca. 10 min",
      "Varm æbletern og bollerne i saucen, smag til og server med ris og æblesalat",
    ]
  },
  {
    id: "stegt-flaesk-persillesauce",
    kategorier: [],
    minutter: 45,
    navn: "Stegt flæsk med persillesauce",
    kategori: "aftensmad",
    koed: "Svinekød",
    portioner: 4,
    ingredienser: [
      { navn: "Flæsk i skiver", maengde: "800 g", soeg: ["svinekød", "flæsk"], vaelgBilligstPerKg: true, estimeret: false },
      { navn: "Kartofler", maengde: "1 kg", soeg: ["kartofler"], vaelgBilligstPerKg: true, estimeret: false },
      { navn: "Smør", maengde: "2 spsk", soeg: ["smør", "smørbar"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Hvedemel", maengde: "2 spsk", soeg: ["hvedemel"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 0 },
      { navn: "Mælk", maengde: "5 dl", soeg: ["mælk"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 6 },
      { navn: "Persille og citron", maengde: "til sauce", soeg: [], estimeret: true, estimereretPris: 5 },
      { navn: "Salt og peber", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Salt flæsket og steg det på en rist i ovnen ved 175° varmluft i 30-40 min — vend et par gange",
      "Kog kartoflerne møre i letsaltet vand, ca. 20 min, og hæld vandet fra",
      "Smelt smør, pisk mel i til en jævn masse og pisk mælken i lidt ad gangen",
      "Kog saucen ca. 5 min, smag til med citron, persille, salt og peber, og server til flæsk og kartofler",
    ]
  },
  {
    id: "flaeskesteg-sprod-svaer",
    kategorier: [],
    minutter: 115,
    navn: "Flæskesteg med sprød svær",
    kategori: "aftensmad",
    koed: "Svinekød",
    portioner: 6,
    ingredienser: [
      { navn: "Flæskesteg (grisekam med svær)", maengde: "2 kg", soeg: ["svinekød", "flæskesteg"], vaelgBilligstPerKg: true, estimeret: false },
      { navn: "Kartofler (til servering)", maengde: "1,5 kg", soeg: ["kartofler"], vaelgBilligstPerKg: true, estimeret: false },
      { navn: "Salt", maengde: "ca. 3 tsk", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Rids sværen helt igennem uden at skære i kødet, gnid salt mellem sværene og lad trække ca. 20 min",
      "Læg stegen i en bradepande med sværen nedad, hæld kogende vand så sværen er dækket, og bag ved 200° varmluft i 20 min",
      "Vend stegen, sørg for at sværen ligger vandret, gnid med salt igen og bag ved 200° varmluft i ca. 1½ time",
      "Skru op til 250° (eller grill) de sidste 10-30 min hvis sværen ikke er sprød — kernetemperatur 65-70°",
      "Lad stegen hvile 15-20 min og server med kogte kartofler",
    ]
  },
  {
    id: "tarteletter-hons-asparges",
    kategorier: [],
    minutter: 90,
    navn: "Tarteletter med høns i asparges",
    kategori: "aftensmad",
    koed: "Kylling",
    portioner: 6,
    ingredienser: [
      { navn: "Hel kylling eller høne", maengde: "ca. 1100 g", soeg: ["kylling", "kyllingebryst"], vaelgBilligstPerKg: true, estimeret: false },
      { navn: "Løg", maengde: "2 stk", soeg: ["løg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Gulerødder", maengde: "2 stk", soeg: ["gulerødder", "gulerodder"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Porrer", maengde: "2 stk", soeg: ["porre", "porrer"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 8 },
      { navn: "Hvide aspargessnitter", maengde: "2 dåser (ca. 510 g)", soeg: [], estimeret: true, estimereretPris: 25 },
      { navn: "Smør", maengde: "50 g", soeg: ["smør", "smørbar"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Hvedemel", maengde: "60 g", soeg: ["hvedemel"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 0 },
      { navn: "Piskefløde", maengde: "1 dl", soeg: ["piskefløde", "fløde"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Tarteletter", maengde: "24 stk", soeg: [], estimeret: true, estimereretPris: 25 },
      { navn: "Laurbær og salt", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Kog kylling/høne med løg, gulerødder, porrer, laurbær og salt under låg ca. 45 min",
      "Tag kødet op, si suppen (gem ca. 3 dl), og riv hønsekødet i trevler",
      "Smelt smør, rør mel i og svits 2 min, tilsæt aspargesvand og bring i kog",
      "Tilsæt suppe og fløde, kog op, vend hønsekød, asparges, salt og peber i og kog forsigtigt 2 min",
      "Lun tarteletterne, fyld dem med høns i asparges og server straks",
    ]
  },
  {
    id: "braendende-kaerlighed",
    kategorier: [],
    minutter: 45,
    navn: "Brændende kærlighed",
    kategori: "aftensmad",
    koed: "Svinekød",
    portioner: 4,
    ingredienser: [
      { navn: "Kartofler", maengde: "1 kg", soeg: ["kartofler"], vaelgBilligstPerKg: true, estimeret: false },
      { navn: "Bacon", maengde: "250 g", soeg: ["bacon"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Løg", maengde: "6 stk (ca. 500 g)", soeg: ["løg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Smør", maengde: "50 g", soeg: ["smør", "smørbar"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Mælk", maengde: "2½ dl", soeg: ["mælk"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 4 },
      { navn: "Syltede rødbeder", maengde: "300 g", soeg: [], estimeret: true, estimereretPris: 15 },
      { navn: "Groft rugbrød", maengde: "240 g", soeg: ["rugbrød", "rugbroed"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Salt og peber", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Kog kartoflerne møre i usaltet vand ca. 20 min, mos dem og rør smør og mælk i til en glat mos — smag til med salt",
      "Steg bacontern sprøde og lad dem dryppe af",
      "Steg løgene i baconfedtet til de er gyldne og bløde, og vend baconen i igen",
      "Server kartoffelmosen med bacon-løg på toppen, syltede rødbeder, et grønt drys og rugbrød ved siden af",
    ]
  },
  {
    id: "biksemad",
    kategorier: [],
    minutter: 60,
    navn: "Biksemad med spejlæg",
    kategori: "aftensmad",
    koed: "Oksekød",
    portioner: 4,
    ingredienser: [
      { navn: "Kartofler", maengde: "1 kg", soeg: ["kartofler"], vaelgBilligstPerKg: true, estimeret: false },
      { navn: "Oksekød (tykstegsbøf)", maengde: "300 g", soeg: ["oksekød", "tykstegsbøf"], vaelgBilligstPerKg: true, estimeret: false },
      { navn: "Løg", maengde: "1 stk", soeg: ["løg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Æg", maengde: "4 stk", soeg: ["æg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Worcestershire sauce", maengde: "2 spsk", soeg: [], estimeret: true, estimereretPris: 0 },
      { navn: "Bearnaise", maengde: "2 dl", soeg: [], estimeret: true, estimereretPris: 12 },
      { navn: "Syltede rødbeder", maengde: "100 g", soeg: [], estimeret: true, estimereretPris: 8 },
      { navn: "Rødløg (syltet)", maengde: "1 stk", soeg: ["løg", "rødløg"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 2 },
      { navn: "Smør/olie og krydderier", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Sylt rødløg i æblecidereddike og sukker i mindst 30 min",
      "Sauter løg bløde, kom kogte kartoffeltern på med smør og rist dem sprøde — smag til med salt, peber og worcestershire",
      "Lynsteg oksekødet i tern i smør (gerne rosa midte) og vend det sammen med kartoflerne",
      "Steg spejlæg og anret biksemad med spejlæg, bearnaise, syltede rødløg og rødbeder, drysset med persille",
    ]
  },
  {
    id: "pikant-kylling-fad",
    kategorier: [],
    minutter: 40,
    navn: "Pikant kylling i fad",
    kategori: "aftensmad",
    koed: "Kylling",
    portioner: 4,
    ingredienser: [
      { navn: "Kyllingeinderfileter", maengde: "300 g", soeg: ["kyllingebryst", "kylling"], vaelgBilligstPerKg: true, estimeret: false },
      { navn: "Løg", maengde: "2 stk", soeg: ["løg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Hvidløg", maengde: "2 fed", soeg: ["hvidløg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Rød chili", maengde: "1 stk", soeg: ["chili"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 5 },
      { navn: "Blandede grøntsager (peberfrugt, porre, squash)", maengde: "750 g", soeg: ["peberfrugt"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 20 },
      { navn: "Flåede tomater", maengde: "400 g", soeg: ["flåede tomater", "hakkede tomater", "tomat"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 8 },
      { navn: "Pikant flødeost", maengde: "200 g", soeg: ["ost", "flødeost"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 18 },
      { navn: "Piskefløde", maengde: "1 dl", soeg: ["piskefløde", "fløde"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 5 },
      { navn: "Perlebyg eller ris", maengde: "320 g", soeg: ["ris"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 12 },
      { navn: "Timian, salt og persille", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Brun kyllingen på en pande og læg den i et ovnfast fad",
      "Svits løg, hvidløg, chili og grøntsager på panden i 3-4 min",
      "Bland flåede tomater, pikantost, fløde, timian, salt og peber sammen til en jævn sauce",
      "Vend grøntsagerne i saucen, hæld det over kyllingen og bag ved 200° varmluft ca. 25 min",
      "Server med perlebyg eller ris og friskhakket persille",
    ]
  },
  {
    id: "klassisk-burger",
    kategorier: [],
    minutter: 30,
    navn: "Klassisk burger",
    kategori: "aftensmad",
    koed: "Oksekød",
    portioner: 4,
    ingredienser: [
      { navn: "Hakket oksekød", maengde: "400 g", soeg: ["hakket oksekød", "hakket dansk oksekød"], vaelgBilligstPerKg: true, estimeret: false },
      { navn: "Bacon", maengde: "8 skiver (ca. 125 g)", soeg: ["bacon"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Lagret cheddarost", maengde: "4 skiver", soeg: ["ost", "cheddar"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 12 },
      { navn: "Burgerboller", maengde: "4 stk", soeg: ["boller", "burgerboller"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 15 },
      { navn: "Mayonnaise", maengde: "1 dl", soeg: ["mayonnaise"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 12 },
      { navn: "Tomater", maengde: "2 stk", soeg: ["tomat"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 8 },
      { navn: "Agurk", maengde: "½ stk", soeg: ["agurk"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 4 },
      { navn: "Rødløg", maengde: "1 stk", soeg: ["løg", "rødløg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Hjertesalat", maengde: "4 blade", soeg: ["salat"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 10 },
      { navn: "Smør og salt", maengde: "lidt", soeg: ["smør", "smørbar"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Steg baconskiverne sprøde og lad dem dryppe af",
      "Form kødet til 4 bøffer, brun dem ca. 1 min på hver side og steg dem færdige ved jævn varme ca. 10 min",
      "Fordel cheddar og bacon på bøfferne, så osten smelter",
      "Lun og flæk burgerbollerne, smør med mayo og saml burgeren med bøf, tomat, agurk, rødløg og salat",
    ]
  },
  {
    id: "marry-me-chicken-orzo",
    kategorier: [],
    minutter: 30,
    navn: "Marry me chicken orzo",
    kategori: "aftensmad",
    koed: "Kylling",
    portioner: 4,
    ingredienser: [
      { navn: "Kyllingebrystfileter", maengde: "2 stk (ca. 300 g)", soeg: ["kyllingebryst", "kylling"], vaelgBilligstPerKg: true, estimeret: false },
      { navn: "Champignon", maengde: "200 g", soeg: ["champignon"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 10 },
      { navn: "Løg", maengde: "2 stk", soeg: ["løg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Hvidløg", maengde: "3 fed", soeg: ["hvidløg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Soltørrede tomater i olie", maengde: "150 g", soeg: [], estimeret: true, estimereretPris: 18 },
      { navn: "Orzo (pastaris)", maengde: "300 g", soeg: ["pasta", "orzo"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Hønsebouillon", maengde: "7½ dl", soeg: ["bouillon"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 4 },
      { navn: "Madlavningsfløde", maengde: "2 dl", soeg: ["piskefløde", "fløde"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Frisk spinat", maengde: "200 g", soeg: ["spinat"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Timian, chiliflager og salt", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Brun kyllingestykkerne i olie ved høj varme ca. 2 min, krydr med salt og peber og tag dem op",
      "Svits champignon ca. 5 min, tilsæt løg, hvidløg, soltørrede tomater, timian og chiliflager og steg ca. 2 min",
      "Tilsæt orzo, bouillon, fløde og salt, kom kyllingen tilbage og lad simre under låg ca. 15 min",
      "Vend spinat i, til det falder sammen, og smag til",
    ]
  },
  {
    id: "marry-me-kodboller",
    kategorier: [],
    minutter: 40,
    navn: "Marry me kødboller",
    kategori: "aftensmad",
    koed: "Kylling",
    portioner: 4,
    ingredienser: [
      { navn: "Hakket kyllingekød", maengde: "300 g", soeg: ["hakket kylling", "kylling"], vaelgBilligstPerKg: true, estimeret: false },
      { navn: "Æg", maengde: "1 stk", soeg: ["æg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Hvedemel", maengde: "1½ spsk", soeg: ["hvedemel"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 0 },
      { navn: "Soltørrede tomater i olie", maengde: "125 g", soeg: [], estimeret: true, estimereretPris: 18 },
      { navn: "Løg", maengde: "2 stk", soeg: ["løg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Hvidløg", maengde: "2 fed", soeg: ["hvidløg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Tomatpuré", maengde: "2 spsk", soeg: ["tomatpuré", "tomatpure"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 4 },
      { navn: "Cherrytomater", maengde: "200 g", soeg: ["tomat", "cherrytomater"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 12 },
      { navn: "Hønsebouillon", maengde: "2 dl", soeg: ["bouillon"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 3 },
      { navn: "Madlavningsfløde", maengde: "2 dl", soeg: ["piskefløde", "fløde"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Peberfrugt", maengde: "2 stk", soeg: ["peberfrugt"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Babyspinat", maengde: "75 g", soeg: ["spinat"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Kartofler (til mos)", maengde: "1 kg", soeg: ["kartofler"], vaelgBilligstPerKg: true, estimeret: false },
      { navn: "Smør, timian, chili og salt", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Rør kyllingefarsen sejt med salt, og tilsæt æg, mel, soltørrede tomater og løg — lad den hvile på køl ca. 15 min",
      "Form kødboller og steg dem gyldne på alle sider ved høj varme ca. 5 min",
      "Smelt smør, rør mel i, tilsæt løg, hvidløg, tomatpuré, tomater, timian og chili og steg ca. 3 min",
      "Kom bouillon, fløde og kødbollerne i og lad simre ca. 10 min",
      "Vend peberfrugt og spinat i, smag til, og server med kartoffelmos",
    ]
  },
  {
    id: "dhal",
    kategorier: [],
    minutter: 45,
    navn: "Dhal med røde linser",
    kategori: "aftensmad",
    koed: "Alt",
    portioner: 4,
    ingredienser: [
      { navn: "Røde linser", maengde: "300 g", soeg: ["linser"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 18 },
      { navn: "Løg", maengde: "3 stk", soeg: ["løg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Hvidløg", maengde: "5 fed", soeg: ["hvidløg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Frisk ingefær", maengde: "1½ spsk", soeg: [], estimeret: true, estimereretPris: 3 },
      { navn: "Hakkede tomater", maengde: "1 dåse (400 g)", soeg: ["hakkede tomater", "tomat"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 8 },
      { navn: "Kokosmælk", maengde: "1 dl", soeg: ["kokosmælk"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 5 },
      { navn: "Tomatpuré", maengde: "2 spsk", soeg: ["tomatpuré", "tomatpure"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 4 },
      { navn: "Grøntsagsbouillon", maengde: "7½ dl", soeg: ["bouillon"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 4 },
      { navn: "Græsk yoghurt", maengde: "2 dl", soeg: ["yoghurt naturel", "yoghurt"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 8 },
      { navn: "Naanbrød", maengde: "2 stk", soeg: [], estimeret: true, estimereretPris: 15 },
      { navn: "Krydderier (garam masala, koriander, chili, kardemomme) og olie", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Steg løg og hvidløg i olie ca. 3 min, tilsæt ingefær og krydderier og steg yderligere ca. 2 min",
      "Skyl linserne, tilsæt dem med bouillonen, bring i kog og lad simre ved svag varme ca. 10 min",
      "Tilsæt tomater, kokosmælk og tomatpuré og kog ca. 5 min, til linserne er møre — smag til",
      "Lad dhalen trække 5 min, top med yoghurt og krydderurter og server med lune naanbrød",
    ]
  },
  {
    id: "teriyaki-nudler",
    kategorier: [],
    minutter: 20,
    navn: "Teriyaki-nudler med grønt",
    kategori: "aftensmad",
    koed: "Alt",
    portioner: 4,
    ingredienser: [
      { navn: "Ægnudler", maengde: "150 g", soeg: ["nudler"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 12 },
      { navn: "Gulerødder", maengde: "2 stk", soeg: ["gulerødder", "gulerodder"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Spidskål", maengde: "½ stk (ca. 200 g)", soeg: ["spidskål"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 8 },
      { navn: "Sesamfrø", maengde: "½ dl", soeg: [], estimeret: true, estimereretPris: 5 },
      { navn: "Teriyakisauce", maengde: "1 dl", soeg: [], estimeret: true, estimereretPris: 15 },
      { navn: "Rød chili", maengde: "½ stk", soeg: ["chili"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 3 },
      { navn: "Lime", maengde: "2 stk", soeg: [], estimeret: true, estimereretPris: 6 },
      { navn: "Smør", maengde: "15 g", soeg: ["smør", "smørbar"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Rist sesamfrøene på en tør pande 2-3 min, og kog nudlerne efter anvisning (gem lidt kogevand)",
      "Smelt smør i en dyb pande og steg gulerødderne ca. 2 min ved høj varme",
      "Tilsæt kål og chili og steg ca. 1 min",
      "Tilsæt nudler, 2 spsk kogevand, teriyakisauce og sesamfrø, pres saft fra én lime over og varm igennem",
      "Smag til og server med limebåde",
    ]
  },
  {
    id: "mexi-bowl",
    kategorier: [],
    minutter: 30,
    navn: "Mexi bowl",
    kategori: "aftensmad",
    koed: "Oksekød",
    portioner: 4,
    ingredienser: [
      { navn: "Hakket oksekød", maengde: "300 g", soeg: ["hakket oksekød", "hakket dansk oksekød"], vaelgBilligstPerKg: true, estimeret: false },
      { navn: "Ris", maengde: "2 dl", soeg: ["ris"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 8 },
      { navn: "Majs", maengde: "150 g", soeg: ["majs"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 8 },
      { navn: "Bønner i chilisauce", maengde: "1 dåse", soeg: ["bønner", "kidneybønner"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 10 },
      { navn: "Hjertesalat", maengde: "2 stk", soeg: ["salat"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 15 },
      { navn: "Avocado", maengde: "2 stk", soeg: ["avocado"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 28 },
      { navn: "Agurk", maengde: "1 stk", soeg: ["agurk"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 8 },
      { navn: "Tomatsalsa", maengde: "300 g", soeg: [], estimeret: true, estimereretPris: 15 },
      { navn: "Crème fraiche", maengde: "4 spsk", soeg: ["creme fraiche"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Tortillachips", maengde: "50 g", soeg: [], estimeret: true, estimereretPris: 8 },
      { navn: "Krydderier (spidskommen, paprika, koriander, løgpulver) og olie", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Kog risene efter anvisning",
      "Rist majsene på en tør pande 2-3 min ved høj varme",
      "Steg oksekødet med krydderierne ved høj varme ca. 5 min",
      "Tilsæt chilibønner, chilisauce, salt og peber og lad simre ca. 5 min — smag til",
      "Anret ris og kød i 4 skåle med salat, avocado, agurk, salsa og øvrige toppings",
    ]
  },
  {
    id: "chow-mein",
    kategorier: [],
    minutter: 30,
    navn: "Chow mein med kylling",
    kategori: "aftensmad",
    koed: "Kylling",
    portioner: 4,
    ingredienser: [
      { navn: "Kyllingebrystfileter", maengde: "400 g", soeg: ["kyllingebryst", "kylling"], vaelgBilligstPerKg: true, estimeret: false },
      { navn: "Ægnudler", maengde: "200 g", soeg: ["nudler"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 15 },
      { navn: "Forårsløg", maengde: "1 bundt", soeg: ["løg", "forårsløg"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 8 },
      { navn: "Gulerod", maengde: "1 stor", soeg: ["gulerødder", "gulerodder"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Rødløg", maengde: "1 stk", soeg: ["løg", "rødløg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Spidskål", maengde: "½ stk (ca. 300 g)", soeg: ["spidskål"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 10 },
      { navn: "Bønnespirer", maengde: "100 g", soeg: [], estimeret: true, estimereretPris: 8 },
      { navn: "Wok-sauce (østerssauce, soja, sukker, majsstivelse)", maengde: "til sauce", soeg: [], estimeret: true, estimereretPris: 5 },
      { navn: "Olie og peber", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Vend kyllingestrimlerne i en marinade af vand, østerssauce, majsstivelse og peber",
      "Rør saucen sammen af østerssauce, soja, sukker og bouillon-pulver, og kog nudlerne efter anvisning",
      "Varm olie og steg kyllingen 3-4 min, tilsæt forårsløg, gulerod og rødløg og steg ca. 4 min",
      "Kom spidskål og nudler i og steg ca. 3 min",
      "Tilsæt sauce, bønnespirer og kylling, vend rundt og kværn peber over",
    ]
  },
  {
    id: "stuvet-spidskal",
    kategorier: ["salat"],
    minutter: 30,
    navn: "Stuvet spidskål",
    kategori: "aftensmad",
    koed: "Alt",
    portioner: 4,
    ingredienser: [
      { navn: "Spidskål", maengde: "1 kg (ca. 2 stk)", soeg: ["spidskål"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 16 },
      { navn: "Mælk", maengde: "3½ dl", soeg: ["mælk"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 5 },
      { navn: "Hvedemel", maengde: "2½ spsk", soeg: ["hvedemel"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 0 },
      { navn: "Smør", maengde: "15 g", soeg: ["smør", "smørbar"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 0 },
      { navn: "Muskatnød, persille, salt og peber", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Flæk spidskålene, fjern stokken og damp kålen i vand og salt under låg ca. 5 min",
      "Tag kålen op (gem kogelagen), lad den dryppe af og hak den groft eller fint",
      "Pisk mel og ½ dl mælk sammen, tilsæt resten af mælken, 1 dl kogelage og smør, og kog saucen ca. 5 min under omrøring",
      "Smag til med muskatnød, salt og peber, vend kålen i og varm igennem ca. 2 min — pynt med persille",
    ]
  },

  // ===== BRØD =====
  {
    id: "focaccia-brod",
    kategorier: ["broed"],
    minutter: 180,
    navn: "Focaccia",
    kategori: "aftensmad",
    koed: "Alt",
    portioner: 6,
    ingredienser: [
      { navn: "Hvedemel", maengde: "500 g", soeg: ["hvedemel"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Gær", maengde: "25 g", soeg: [], estimeret: true, estimereretPris: 3 },
      { navn: "Sukker", maengde: "2 tsk", soeg: ["sukker"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 0 },
      { navn: "Olivenolie", maengde: "8 spsk", soeg: [], estimeret: true, estimereretPris: 5 },
      { navn: "Rosmarin og flagesalt", maengde: "til topping", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Rør gæren ud i lillefingervarmt vand, tilsæt sukker og mel og ælt dejen blank og smidig — tilsæt salt efter ca. 5 min",
      "Lad dejen hæve lunt og tildækket ca. 1½ time",
      "Bred dejen ud i en oliesmurt bradepande med bagepapir og lad den efterhæve ca. 1 time",
      "Dryp med olie, tryk fingrene dybt ned i dejen, drys med rosmarin og salt",
      "Bag ca. 25 min ved 200° varmluft",
    ]
  },
  {
    id: "surdejsbrod",
    kategorier: ["broed"],
    minutter: 60,
    navn: "Surdejsbrød",
    kategori: "aftensmad",
    koed: "Alt",
    portioner: 6,
    ingredienser: [
      { navn: "Hvedemel", maengde: "300 g", soeg: ["hvedemel"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Tipo 00 hvedemel", maengde: "200 g", soeg: ["hvedemel"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 8 },
      { navn: "Surdej", maengde: "150 g", soeg: [], estimeret: true, estimereretPris: 0 },
      { navn: "Honning", maengde: "1 spsk", soeg: ["honning"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 2 },
      { navn: "Salt", maengde: "1 spsk", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Rør vand, surdej og honning sammen, tilsæt mel og salt og ælt dejen blank og elastisk ca. 10 min",
      "Kom dejen i en oliesmurt skål med låg og lad den hæve i køleskabet 12-24 timer",
      "Fold siderne op på dejen, vend den om og lad den efterhæve på bagepapir ca. 1 time",
      "Træk brødet over på en varm plade, giv det et snit og bag ca. 15 min ved 250°, derefter ca. ½ time ved 200°",
    ]
  },
  {
    id: "nemme-kernestykker",
    kategorier: ["broed"],
    minutter: 75,
    navn: "Nemme kernestykker med ske",
    kategori: "aftensmad",
    koed: "Alt",
    portioner: 12,
    ingredienser: [
      { navn: "Hvedemel", maengde: "500 g", soeg: ["hvedemel"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Fuldkornshvedemel", maengde: "2 dl (ca. 100 g)", soeg: ["hvedemel", "fuldkornsmel"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 4 },
      { navn: "Havregryn", maengde: "4 dl (ca. 125 g)", soeg: ["havregryn"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 5 },
      { navn: "Kærnemælk eller A38", maengde: "3 dl", soeg: ["mælk", "kærnemælk"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 4 },
      { navn: "Revet gulerod eller squash", maengde: "100 g", soeg: ["gulerødder", "gulerodder"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 3 },
      { navn: "Blandede kerner og frø", maengde: "2 dl", soeg: [], estimeret: true, estimereretPris: 10 },
      { navn: "Gær", maengde: "10 g", soeg: [], estimeret: true, estimereretPris: 2 },
      { navn: "Salt", maengde: "1½ tsk", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Rør vand, syrnet mejeriprodukt, gær, revet grønt, havregryn, fuldkornsmel og salt sammen",
      "Tilsæt hvedemel og slå dejen sammen med en grydeske til en fugtig dej, drys kerner over, dæk og stil på køl natten over (mindst 8 timer)",
      "Form boller med en våd ske på en plade med bagepapir",
      "Bag straks ved 250° varmluft i 15-20 min med damp (hæld 1 dl vand i en varm bradepande), og hold lågen lukket",
    ]
  },
  {
    id: "hytteostboller",
    kategorier: ["broed"],
    minutter: 40,
    navn: "Hytteostboller",
    kategori: "aftensmad",
    koed: "Alt",
    portioner: 10,
    ingredienser: [
      { navn: "Hytteost", maengde: "500 g", soeg: ["hytteost"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Havregryn", maengde: "400 g", soeg: ["havregryn"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 8 },
      { navn: "Æg", maengde: "5 stk (+ til pensling)", soeg: ["æg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Kerner (græskar eller solsikke)", maengde: "2 dl", soeg: [], estimeret: true, estimereretPris: 10 },
      { navn: "Salt", maengde: "1 tsk", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Rør hytteost, havregryn, æg, kerner og salt sammen til en grov dej",
      "Form 10 boller på en plade med bagepapir",
      "Pensl med sammenpisket æg og pynt evt. med ekstra kerner",
      "Bag 25-30 min ved 200° varmluft til de er gyldne og gennembagte, og lad dem køle på en rist",
    ]
  },
  {
    id: "gulerodsboller",
    kategorier: ["broed"],
    minutter: 95,
    navn: "Gulerodsboller",
    kategori: "aftensmad",
    koed: "Alt",
    portioner: 18,
    ingredienser: [
      { navn: "Hvedemel", maengde: "700 g", soeg: ["hvedemel"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Gulerødder", maengde: "3 stk (ca. 225 g)", soeg: ["gulerødder", "gulerodder"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Mælk", maengde: "2 dl", soeg: ["mælk"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 3 },
      { navn: "Æg", maengde: "1½ stk (+ til pensling)", soeg: ["æg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Havregryn", maengde: "60 g (ca. 2 dl)", soeg: ["havregryn"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 0 },
      { navn: "Gær", maengde: "25 g", soeg: [], estimeret: true, estimereretPris: 3 },
      { navn: "Salt", maengde: "2 tsk", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Rør gæren ud i lillefingervarmt vand, tilsæt gulerødder og de øvrige ingredienser (hold lidt mel tilbage) og slå dejen sammen",
      "Lad dejen hæve lunt og tildækket ca. 45 min",
      "Ælt dejen igennem, form 18 boller og lad dem efterhæve ca. 10 min",
      "Pensl med sammenpisket æg og bag ca. 20 min ved 200°",
    ]
  },
  {
    id: "fodselsdagsboller",
    kategorier: ["broed"],
    minutter: 150,
    navn: "Fødselsdagsboller",
    kategori: "aftensmad",
    koed: "Alt",
    portioner: 12,
    ingredienser: [
      { navn: "Hvedemel", maengde: "500 g", soeg: ["hvedemel"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Smør", maengde: "150 g", soeg: ["smør", "smørbar"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Mælk", maengde: "3 dl", soeg: ["mælk"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 4 },
      { navn: "Sukker", maengde: "3 spsk", soeg: ["sukker"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 0 },
      { navn: "Æg", maengde: "til pensling", soeg: ["æg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Gær", maengde: "25 g", soeg: [], estimeret: true, estimereretPris: 3 },
      { navn: "Salt", maengde: "1 tsk", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Smelt smørret, hæld det i en skål med mælk og opløs gæren heri, og tilsæt sukker og salt",
      "Tilsæt melet (hold lidt tilbage), slå dejen sammen og lad den hæve lunt og tildækket ca. 45 min",
      "Form 12 boller og lad dem efterhæve tildækket ca. 1 time",
      "Pensl med æg og bag 15-20 min ved 200° til de er gyldne",
    ]
  },
  {
    id: "polsehorn",
    kategorier: ["broed"],
    minutter: 120,
    navn: "Pølsehorn",
    kategori: "aftensmad",
    koed: "Svinekød",
    portioner: 6,
    ingredienser: [
      { navn: "Hvedemel", maengde: "400 g (ca. 7 dl)", soeg: ["hvedemel"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Wienerpølser", maengde: "6 stk", soeg: ["pølser", "wienerpølser"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Mælk", maengde: "¼ liter", soeg: ["mælk"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 3 },
      { navn: "Smør", maengde: "25 g", soeg: ["smør", "smørbar"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 0 },
      { navn: "Sukker", maengde: "2 tsk", soeg: ["sukker"], vaelgBilligstPerKg: false, estimeret: true, estimereretPris: 0 },
      { navn: "Gær", maengde: "25 g", soeg: [], estimeret: true, estimereretPris: 3 },
      { navn: "Salt og evt. sesamfrø", maengde: "lidt", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Smelt smørret, tilsæt mælken, hæld i en skål og rør gæren ud heri",
      "Tilsæt de øvrige tørre ingredienser (hold lidt mel tilbage), slå dejen sammen og lad den hæve ca. 1 time",
      "Rul dejen ud, skær den i trekanter, halver pølserne og rul dejen om dem fra den brede ende",
      "Lad pølsehornene efterhæve ca. 15 min, pensl med vand, drys evt. med sesamfrø og bag ca. 20 min ved 200°",
    ]
  },

  // ===== DESSERTER =====
  {
    id: "pandekager",
    kategorier: ["dessert"],
    minutter: 30,
    navn: "Klassiske pandekager",
    kategori: "dessert",
    koed: "Alt",
    portioner: 4,
    ingredienser: [
      { navn: "Hvedemel", maengde: "250 g (ca. 4 dl)", soeg: ["hvedemel"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Mælk", maengde: "½ liter", soeg: ["mælk"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Æg", maengde: "3 stk", soeg: ["æg", "aeg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Sukker", maengde: "2 spsk", soeg: ["sukker"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Smør (til stegning)", maengde: "25 g", soeg: ["smør", "smørbar"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Vaniljesukker", maengde: "1 tsk", soeg: [], estimeret: true, estimereretPris: 0 },
      { navn: "Salt", maengde: "1 knivspids", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Pisk æg og sukker sammen, og rør melet i skiftevis med halvdelen af mælken, til dejen er glat",
      "Spæd med resten af mælken og tilsæt vaniljesukker og salt — lad dejen hvile 15-30 min",
      "Steg tynde pandekager på en varm pande med lidt smør, ca. 1-2 min på hver side",
      "Server med sukker, syltetøj eller frisk frugt",
    ]
  },
  {
    id: "aeblekage",
    kategorier: ["dessert"],
    minutter: 40,
    navn: "Gammeldags æblekage",
    kategori: "dessert",
    koed: "Alt",
    portioner: 4,
    ingredienser: [
      { navn: "Æbler", maengde: "6 stk (ca. 800 g)", soeg: [], vaelgBilligstPerKg: true, estimeret: true, estimereretPris: 18 },
      { navn: "Havregryn", maengde: "100 g", soeg: ["havregryn"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Sukker", maengde: "100 g", soeg: ["sukker"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Smør", maengde: "50 g", soeg: ["smør", "smørbar"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Piskefløde", maengde: "2,5 dl", soeg: ["piskefløde", "fløde"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Vaniljesukker", maengde: "1 tsk", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Skræl og skær æblerne i både, og kog dem møre med halvdelen af sukkeret og lidt vand til en grov æblegrød — lad den køle af",
      "Rist havregryn, resten af sukkeret og smørret på en pande, til det er gyldent og sprødt — lad det køle",
      "Pisk fløden til skum med vaniljesukker",
      "Lag æblegrød, ristede havregryn og flødeskum i glas eller skål, og slut med flødeskum og lidt ristet drys",
    ]
  },
  {
    id: "chokoladekage",
    kategorier: ["dessert"],
    minutter: 45,
    navn: "Saftig chokoladekage",
    kategori: "dessert",
    koed: "Alt",
    portioner: 8,
    ingredienser: [
      { navn: "Hvedemel", maengde: "200 g", soeg: ["hvedemel"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Sukker", maengde: "300 g", soeg: ["sukker"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Æg", maengde: "3 stk", soeg: ["æg", "aeg"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Smør", maengde: "150 g", soeg: ["smør", "smørbar"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Mælk", maengde: "1,5 dl", soeg: ["mælk"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Kakao", maengde: "50 g", soeg: [], estimeret: true, estimereretPris: 8 },
      { navn: "Bagepulver", maengde: "1 tsk", soeg: [], estimeret: true, estimereretPris: 0 },
      { navn: "Vaniljesukker", maengde: "2 tsk", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Pisk blødt smør og sukker hvidt, og pisk æggene i ét ad gangen",
      "Bland mel, kakao, bagepulver og vaniljesukker, og vend det i skiftevis med mælken",
      "Hæld dejen i en smurt form (ca. 20×30 cm) og bag ved 180° i ca. 25-30 min",
      "Lad kagen køle lidt, og pynt evt. med flormelis eller en simpel glasur",
    ]
  },
  {
    id: "havregrynskugler",
    kategorier: ["dessert"],
    minutter: 15,
    navn: "Havregrynskugler (uden bagning)",
    kategori: "dessert",
    koed: "Alt",
    portioner: 6,
    ingredienser: [
      { navn: "Havregryn", maengde: "150 g", soeg: ["havregryn"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Smør", maengde: "100 g", soeg: ["smør", "smørbar"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Sukker", maengde: "75 g", soeg: ["sukker"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Kakao", maengde: "3 spsk", soeg: [], estimeret: true, estimereretPris: 8 },
      { navn: "Kokosmel (til rulning)", maengde: "50 g", soeg: [], estimeret: true, estimereretPris: 6 },
      { navn: "Vaniljesukker", maengde: "1 tsk", soeg: [], estimeret: true, estimereretPris: 0 },
    ],
    fremgangsmaade: [
      "Rør blødt smør sammen med sukker, kakao og vaniljesukker til en ensartet masse",
      "Rør havregrynene i, til dejen er fast nok til at forme",
      "Form små kugler med hænderne og rul dem i kokosmel",
      "Stil kuglerne koldt mindst 30 min, så de bliver faste — opbevares i køleskab",
    ]
  },
  {
    id: "risalamande",
    kategorier: ["dessert"],
    minutter: 60,
    navn: "Risalamande med kirsebærsauce",
    kategori: "dessert",
    koed: "Alt",
    portioner: 6,
    ingredienser: [
      { navn: "Grødris", maengde: "150 g", soeg: ["grødris", "ris"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Mælk", maengde: "1 liter", soeg: ["mælk"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Piskefløde", maengde: "5 dl", soeg: ["piskefløde", "fløde"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Sukker", maengde: "75 g", soeg: ["sukker"], vaelgBilligstPerKg: false, estimeret: false },
      { navn: "Smuttede mandler", maengde: "100 g", soeg: [], estimeret: true, estimereretPris: 20 },
      { navn: "Vaniljesukker", maengde: "2 tsk", soeg: [], estimeret: true, estimereretPris: 0 },
      { navn: "Kirsebærsauce", maengde: "1 glas", soeg: [], estimeret: true, estimereretPris: 18 },
    ],
    fremgangsmaade: [
      "Kog risengrød på mælken: bring i kog, skru ned og lad det simre under låg i ca. 35-40 min under jævnlig omrøring — lad den køle helt af",
      "Hak mandlerne groft (gem en hel til mandelgaven), og rør dem i den kolde grød sammen med sukker og vaniljesukker",
      "Pisk fløden til skum og vend den forsigtigt i, til risalamanden er let og luftig",
      "Server kold med varm kirsebærsauce",
    ]
  },
];
